codecov/shared

setup.py

new shared version 0.11.2

---

shared/celery_config.py

adding pre process task name

---

shared/validation/install.py

Fixes: https://github.com/codecov/engineering-team/issues/455
Accompanies: https://github.com/codecov/worker/pull/133

Add health_check field to setup yaml

---

.pre-commit-config.yaml
requirements.txt

as title
to install:
```
pip install -r requirements.txt
pre-commit install
```

add pre-commit config to shared + lint hook

---

shared/analytics_tracking/marketo.py
tests/unit/analytics_tracking/test_marketo.py

https://github.com/codecov/engineering-team/issues/468

specify marketo events that should be sent

---

setup.py
shared/metrics/__init__.py

add prometheus python client dependency

---

shared/reports/readonly.py
shared/reports/resources.py
tests/unit/reports/test_readonly.py

Once incorporated into worker can be used to fix https://codecov.sentry.io/issues/4597918964/

fix: Add report size method

---

shared/validation/user_schema.py

Related: https://github.com/codecov/worker/pull/176

Add partials_as_hits option to cobertura parser options

---

Makefile
shared/github/__init__.py
shared/torngit/github.py
shared/torngit/github_enterprise.py
tests/unit/torngit/test_github.py
tests/unit/torngit/test_github_enterprise.py

Adding host override tech

---

tests/unit/validation/test_install_validation.py

Fixes: https://github.com/codecov/engineering-team/issues/872

tests: update test_install_validation to check for warnings

---

setup.py

Fixes: https://github.com/codecov/internal-issues/issues/160#event-11445671389

update cryptography version to patch vuln

---

.github/workflows/ci.yml

Uploads test results to codecov

build: upload test results

---

shared/bundle_analysis/report.py

fix: BA get bundle reports double session

---

shared/rollouts/__init__.py

fix: add async interface

---

shared/torngit/github.py
tests/integration/test_github.py

feat: add lowercase feature to prev fn

---

setup.py

vulnerability - details here https://github.com/codecov/internal-issues/issues/294

upgrade cryptography version

---

shared/bundle_analysis/models.py
shared/celery_config.py
shared/reports/enums.py
shared/reports/resources.py
shared/rollouts/__init__.py
shared/validation/install.py
tests/unit/reports/test_enums.py

Not much, most of the work is done [here](https://github.com/codecov/worker/pull/347). Also a small quality of life change for refreshing feature flags when developing.

feat: parallel upload processing

---

tests/unit/torngit/test_github.py
tests/unit/torngit/test_gitlab.py

Some asserts were not done properly.

chore: Fix some asserts in tests

---

shared/torngit/github.py

This PR aims to fix an insidious bug around github tokens and their GQL api.
High level here is the issue:
- Something about the token we use when calling the GQL endpoint only fetches back public repos locally
- This can be an issue if a user only has private repos, of which none of them "belong" to the user, meaning none would be pulled back from the "fetch number of repos" call.
- If no repos are returned from the fetch number of repos call, we never actually fetch any pages of repos later on in the generator function
- If no repos are fetched, the owner's permissions for any repos they may have had get removed
- If the permissions get removed, none of them show up on their repo list.
- If none show up on their repo list, the client is unhappy :(
The fix:
- Got rid of the GQL fetch for …

fix: remove GQL fetch repos fn for sync repos generator task

---

shared/bundle_analysis/parser.py
shared/config/__init__.py
tests/samples/sample_bundle_stats_invalid_name.json
tests/unit/bundle_analysis/test_bundle_analysis.py

Check that the bundle name is valid format.
fixes: https://github.com/codecov/engineering-team/issues/1255

add a bundle name validator

---

.github/workflows/ci.yml

Add merge group

---

shared/torngit/github.py

Fixes https://github.com/codecov/internal-issues/issues/448

overlapping variable naming

---

shared/django_apps/db_settings.py
shared/django_apps/dummy_settings.py
shared/django_apps/legacy_migrations/management/commands/migrate.py
shared/torngit/github.py

Updating the shared db django settings to be used in worker/api

update the shared django settings

---

shared/bundle_analysis/parser.py
shared/typings/torngit.py

fix: typing issue because api is on 3.9 still

---

shared/torngit/gitlab.py
tests/integration/test_gitlab.py
tests/unit/torngit/test_gitlab.py

Part of https://github.com/codecov/engineering-team/issues/1167, this is for GitLAB calls, as I continue with the other git providers.
We want to know who's making all these calls! So I added some Counters.

Add count_and_get_url_template to gitlab handler

---

setup.py

Have not done a python package upgrade before. Please let me know if I'm doing this wrong.

chore: Upgrade Requests to 2.32.3

---

shared/django_apps/codecov_auth/models.py

didn't realize I needed to add an app_label to each model

add app_label to new models

---

shared/django_apps/db_settings.py

Worker needs access to this variable, move it from api to shared

move this value from api to shared

---

shared/reports/resources.py
shared/reports/types.py

Debug ReportFileSummary slowness

---

Makefile
shared/bots/helpers.py
tests/unit/bundle_analysis/test_bundle_analysis.py

Seeing this error in Sentry, https://codecov.sentry.io/issues/5619546766/?project=4165036&query=is%3Aunresolved+issue.priority%3A%5Bhigh%2C+medium%5D&referrer=issue-stream&statsPeriod=1h&stream_index=2, as a consequence of my recent change. I missed there was a helper wrapper fn, so I'm adding that in this PR
Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. In 2022 this entity acquired Codecov and as result Sentry is going to need some rights from me in order to utilize my contributions in this PR. So here's the deal: I retain all rights, title and interest in and to my contributions, and by keeping this boilerplate intact I confirm that Sentry can use, modify, copy, and redistribute my contributions, …

Add helper funciton missed in the porting

---

shared/django_apps/codecov_auth/models.py
tests/unit/django_apps/codecov_auth/test_codecov_auth_models.py

add 2 count properties to Account

---

shared/django_apps/codecov_auth/models.py
tests/unit/django_apps/codecov_auth/test_codecov_auth_models.py

Planning to use these fields for the read-only experience in api

add more model properties to Account

---

shared/torngit/github.py
tests/unit/torngit/test_github.py

closes: codecov/engineering-team#2166

log installation making GH request

---

shared/license/__init__.py
tests/unit/test_license.py

for https://github.com/codecov/engineering-team/issues/2000
going to call this from the startup of worker and api

add license logging back to startup

---

shared/bundle_analysis/report.py
tests/unit/bundle_analysis/test_bundle_analysis.py

- Has an option to get list of assets ordered by name or size columns.
- Add `id` attribute to asset report, this will be useful for implementing pagination on the api side.

bundle analysis: introduce asset ordering in query

---

shared/bots/github_apps.py
tests/unit/bots/test_github_apps.py

Improving on previous work that suspends installations when GitHub tell us they are suspended,
we are now also:
* Deleting installatons that can't be found;
* Cleaning up legacy integrations if they are bad.
This should reduce the number of `InvalidInstallationError` we receive from installations that we can't get a
token for.
In contrast it might increase the number of `RepositoryWithoutValidBotError`, if there are no other valid credentials
other than the invalid installation. But that is a different problem for us to fix.
closes https://github.com/codecov/internal-issues/issues/807
closes https://github.com/codecov/internal-issues/issues/809
Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. In 2022 this …

fix: handle better InvalidInstallationError sync

---

shared/bundle_analysis/comparison.py
shared/bundle_analysis/parsers/v1.py
shared/bundle_analysis/parsers/v2.py
shared/bundle_analysis/report.py
shared/bundle_analysis/storage.py

add tracing to BA classes

---

shared/django_apps/core/tests/factories.py
shared/reports/api_report_service.py
shared/reports/filtered.py
shared/reports/resources.py
tests/unit/reports/samples/test_filtered.py
tests/unit/test_report.py

part of https://github.com/codecov/engineering-team/issues/2554

Remove `report_builder` feature

---

shared/bundle_analysis/report.py

closes: https://github.com/codecov/engineering-team/issues/2659

bundle analysis: fix integrity error when ingesting new bundle

---

shared/torngit/github.py

long-boiiii

---

shared/reports/types.py
shared/utils/merge.py

In particular `merge_missed_branches` is showing up in profiles, so it does make sense to optimize that function a little bit.

Optimize some merge-related functions

---

shared/validation/install.py
shared/validation/user_schema.py

Adds a YAML field to hide codecov token to non-admin users. A follow up PR will be added in API that reads the config before sending token values via GQL. 

Add hide codecov tokens field

---

shared/metrics/__init__.py

Add gauges to metrics and support counters with no labels

feat: Add gauges to metrics and support counters with no labels

---

shared/torngit/github.py

Reverts codecov/shared#434. Realized this is not the approach I want to take.

Revert "2876 remove copilot btn from ba pr comment"

---

shared/plan/service.py
shared/self_hosted/service.py
tests/unit/self_hosted/test_self_hosted.py

Moving plan service to shared as part of the new plan work. Moved self hosted stuff, plan service depends on them.

chore: Move plan service missing logic to shared

---

pyproject.toml
shared/bots/__init__.py
shared/bots/github_apps.py
shared/bots/helpers.py
shared/github/__init__.py
shared/rate_limits/__init__.py
shared/typings/torngit.py
tests/unit/bots/test_bots.py
tests/unit/bots/test_bots_helpers.py
uv.lock

Series of commits with small, chore-type changes to improve a little bit some types in random places of shared (the type fixes that seem easy to do, or randomly picked from the list that mypy displays)
Might be easier to review commit-by-commit

Improve typing

---

shared/bundle_analysis/comparison.py
tests/samples/sample_bundle_stats_zero_size_asset.json
tests/unit/bundle_analysis/test_bundle_comparison.py

fix: Bundle Analysis - handle case where asset size is 0

---

shared/events/amplitude/publisher.py
shared/events/amplitude/types.py
tests/unit/events/test_amplitude.py

This PR disables Amplitude when not on prod and also adds a new event type `User Logged in`.

feat: Disable Amplitude when not on prod

---

.github/workflows/upload-overwatch.yml

Integrate overwatch to CI

---

shared/storage/minio.py
tests/unit/storage/test_minio.py
tests/unit/storage/test_new_minio.py

This reverts https://github.com/codecov/shared/pull/562, which I believe has caused 
[WORKER-RPN](https://codecov.sentry.io/issues/6389188602/) and similar problems, which have caused problems when deploying the update in worker.

Revert "chore: fix minio config defaults (#562)"

---

shared/storage/__init__.py
shared/storage/minio.py
tests/unit/storage/test_init.py
tests/unit/storage/test_new_minio.py

So far, this only removes the feature flag and the branches in code. It does not yet clean up all the now-obsolete code, which will follow later.

Hardcode the new minio write implementation

---

shared/rollouts/__init__.py
tests/unit/test_rollouts.py

need to remove exposure logging logic and ship it in both worker and api before the `FeatureExposure` and `SimpleMetric` models can be removed in https://github.com/codecov/shared/pull/571

remove exposure logging from Feature

---

shared/django_apps/core/managers.py

The only usage of this was within tests, which I am removing in https://github.com/codecov/codecov-api/pull/1262

Remove unused `get_aggregated_coverage` QuerySet combinator
