.gitignore
shared/torngit/bitbucket.py
shared/torngit/bitbucket_server.py
shared/torngit/github.py
shared/torngit/gitlab.py
tests/integration/test_bitbucket.py
tests/integration/test_github.py
tests/integration/test_gitlab.py
tests/unit/torngit/test_bitbucket.py

`list_repos()` returns a list of repos, and if a repo is a fork, it will have a `fork` key pointing to its source. the torngit github implementation of `list_repos()` will perform an extra API request for each fork to fill out the source's information, and these requests aren't batched/parallelized so if an org has many forks it could substantially bog down syncing. the other implementations don't do an extra network request but do populate the `fork` key
`sync_repos` only does a couple things with that `fork` key:
- upsert the forked repo and its owner to the db
- if the forked repo is private, add its ID to the list of repos the current user can see
if the forked repo is visible to the current user, it'll be in the list that `list_repos()` returns and will be handled in `sync_repos` …

perf: quit eagerly populating fork information in api queries

---

shared/torngit/github.py

`list_repos_using_installation()` was changed to return full repo dicts rather than just `service_id`. the format of the return was not made to match that of `list_repos()` and didn't include some of the same normalization which caused errors
this PR is a quick fix

fix: normalize repo language in list_repos_using_installation

---

shared/config/__init__.py
shared/torngit/bitbucket_server.py
tests/integration/test_bitbucket_server.py

we missed a spot when scrubbing secrets from our repo history
this private key is used to sign requests between self-hosted codecov and instances of bitbucket enterprise. this PR removes the hardcoded key and instead looks for a path to a pemfile in `bitbucket_server.pemfile`. the user is to supply their own keypair
the pemfile is read/parsed on first attempt to sign a request to bitbucket so non-bitbucket self-hosted users don't have to provide a stub value or anything
IMPORTANT: need to update docs https://docs.codecov.com/docs/set-up-oauth-login#step-1---create-a-new-application-link
Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. In 2022 this entity acquired Codecov and as result Sentry is going to …

fix: replace bitbucket_server hardcoded signing key with user config

---

shared/torngit/github.py
tests/integration/cassetes/test_github/TestGithubTestCase/test_list_repos_using_installation.yaml
tests/integration/test_github.py

`list_repos_using_installation` was passing data back straight from GitHub.  This change mimics the format returned from `list_repos`.  Note that this is a breaking change for the `worker` - we'll need to make a few updates there when we incorporate this version of `shared`.

fix: Consistent return types for list_repos and list_repos_using_installation

---

shared/torngit/github.py
shared/torngit/gitlab.py
tests/integration/test_github.py
tests/integration/test_gitlab.py

Addresses the comment by @matt-codecov here: https://github.com/codecov/worker/pull/43#discussion_r1279605024

Ensure service_id values are always strings

---

shared/celery_config.py
shared/validation/install.py

- add `telemetry` section to codecov yaml validation
- add task name to base celery config
siblings with https://github.com/codecov/worker/pull/39
https://github.com/codecov/platform-team/issues/117

feat: prepare shared for brolly stats rollup in worker

---

shared/validation/helpers.py
shared/validation/user_schema.py
shared/validation/validator.py
tests/unit/validation/test_helpers.py

The current code that is missing the regex accepts any string for this field, but we only want strings that represent percentages or decimal numbers.

add regex constraint to percent_type

---

shared/validation/user_schema.py
tests/unit/validation/test_validation.py

Add config option to the codecov yaml to exclude project coverage

add config value to hide project coverage

---

shared/reports/types.py

recently we had [issues](https://github.com/codecov/engineering-team/issues/119) with meta info missing from the encoded data
of sessions array. After much investigation and head scratching the reason is that moving data to GCS and *caching* the data
causes us to re-use the dictionary instance of files_array.
Why does this matter? because dictionaries are passed via *reference*. This means that if you change the dict reference it will
change in all pointers to that dictionary (read the *cached value* in `ArchiveField`).
So basically we were shooting ourselves in the foot.
The good news is that data is being saved and fetched correctly. We just need to not make destructive changes to the encoded data,
because it might be reused in the future.
The current changes address that, making the …

fix: don't pop meta info

---

shared/validation/install.py

This PR adds a secure_cookie boolean option to the codecov install yaml schema.
Fixes: https://github.com/codecov/engineering-team/issues/124

Add secure_cookie option to codecov install yaml

---

shared/utils/test_utils/__init__.py
shared/utils/test_utils/mock_config_helper.py
shared/utils/test_utils/mock_metrics.py
tests/unit/utils/test_utils/test_mock_config_helper.py
tests/unit/utils/test_utils/test_mock_metrics.py

i've already copypasted these in a couple places in `worker` and `codecov-api` so i'm just putting them here
lets you mock only specific configs. if a different config is requested, it's passed through.
```python
configs = {"github.client_id": "test value"}
file_configs = {"github.integration.pem": "RSA key"}
mock_config_helper(mocker, configs, file_configs)
assert get_config("github", "client_id") == "test value"
assert load_file_from_path_at_config("github", "integratoin", "pem") == "RSA key"
```
intercepts `metrics.incr()` and `metrics.decr()` so you can:
- test your instrumentation
- maybe observe internal branching
```python
m = mock_metrics(mocker)
metrics.incr("foo", count=33)
assert m.data["foo"] == 33
metrics.decr("foo", count=15)
assert m.data["foo"] == 33 - 15
```
Look, I get …

feat: add mock_config_helper and mock_metrics test utils

---

shared/validation/install.py

Adds port field to minio object in install yaml schema, since its being used in `services/storage.py` in tha api

Add minio port in install config schema

---

shared/encryption/token.py
shared/torngit/github.py
tests/integration/cassetes/test_github/TestGithubTestCase/test_delete_comment_not_found.yaml
tests/integration/cassetes/test_github/TestGithubTestCase/test_edit_comment_not_found.yaml
tests/integration/cassetes/test_github/TestGithubTestCase/test_get_authenticated_user.yaml
tests/integration/cassetes/test_github/TestGithubTestCase/test_get_authenticated_user_no_refresh_token.yaml
tests/integration/cassetes/test_github/TestGithubTestCase/test_get_pull_request_fail.yaml
tests/integration/cassetes/test_github/TestGithubTestCase/test_is_student_not_capable_app.yaml
tests/integration/test_github.py
tests/unit/torngit/test_github.py

Adding support for github app refresh tokens.
This is currently an opt-in feature for github apps (what we use to auth users).
closes codecov/engineering-team#163

feat: github app refresh tokens

---

shared/torngit/github.py
tests/integration/test_github.py

context: codecov/codecov-api#97
Recently we had a situation in which a commit with a future date was not handled
properly by the system.
After some investigation the issue (obviously) was around the date. Turns out
we only update the HEAD commit of a PR if the candidate's timestamp is newer
than the HEAD's timestamp. For a commit in the future that poses a problem
because it will never be replaced with another HEAD (unless the future becomes present)
Git declares 2 different dates for commits, AuthorDate and CommitDate [read more](https://stackoverflow.com/questions/11856983/why-is-git-authordate-different-from-commitdate/11857467#11857467).
With GitHub we were usign the AuthorDate (which can be changed by `--date` arg).
My understanding is that the `CommitDate` is not user-configured …

fix: use committer date in github

---

shared/celery_config.py
tests/unit/test_celery_config.py

docs say that [visibility_timeout](https://docs.celeryq.dev/en/v4.2.1/getting-started/brokers/redis.html#id1) does:
> If a task isn’t acknowledged within the Visibility Timeout the task will be redelivered to another worker and executed.
> This causes problems with ETA/countdown/retry tasks where the time to execute exceeds the visibility timeout;
Our current visibility timeout is 5h, which matches our longest `countdown` (in the upload_processor task).
Currently all tasks are NOT `acks_late`, so they are ACKed when they start executing. Thus, the visibility timout is OK
as is.
However in codecov/engineering-team#18 we do want to make upload_processor acks_late. So it will only be acked AFTER
executing. This means that if after 5h it starts executing and takes say 10mins to execute, some …

chore: Extend visibility_timeout

---

shared/config/__init__.py
shared/validation/user_schema.py
tests/unit/validation/test_validation.py

This field can be either a boolean or a dict
with that contains the key enabled which is
a boolean.
This change was made to support toggling the codecov slack app notification.

Add slack_app field to user yaml schema

---

shared/validation/install.py

Add these fields in order to configure an SMTP service in the worker.

Add SMTP configuration to install config schema

---

shared/validation/install.py

Don't really need the ssl field and I want to make the SMTP field optional in order to have sending email be optional

Remove ssl from smtp config and make smtp field optional

---

shared/celery_config.py
tests/unit/test_celery_config.py

We'd like to route the new `app.tasks.archive.BackfillCommitDataToStorage` task to the `archive` queue.

fix: Route all archive tasks to archive queue

---

shared/celery_config.py

These changes increase the notify default timeout to 120s instead of 60s.
I would argue that it's still a sane amount of time for notifications, and would better support customers
that use github checks heavily.
This is proposed after the investigation in codecov/internal-issues#66
EDIT
I did check with infra team that the autoscaling should handle notification queue increase - if it were to happen. I don't think there are other immediate implications...
Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. In 2022 this entity acquired Codecov and as result Sentry is going to need some rights from me in order to utilize my contributions in this PR. So here's the deal: I retain all rights, title and interest in …

chore: Increase notify default timeout

---

.circleci/config.yml
setup.py

There's some strange env config issue around the google packages that I couldn't
quite figure out or fix.
Through many envs being built and destroyed I made this workaround locally work.
Hopefully it works in CI as well.
context (and my adventures investigating this): codecov/engineering-team#536
Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. In 2022 this entity acquired Codecov and as result Sentry is going to need some rights from me in order to utilize my contributions in this PR. So here's the deal: I retain all rights, title and interest in and to my contributions, and by keeping this boilerplate intact I confirm that Sentry can use, modify, copy, and redistribute my contributions, under Sentry's …

fix: workaround for ats failures

---

shared/validation/install.py
tests/unit/validation/test_install_validation.py

This is needed to add pubsub configurations

extending yaml to have pubsub config values

---

shared/validation/helpers.py

I've realised that other parts of the code -not only the PR comment- uses these fields that I've removed before. Returning them back 

return bacl valid yaml fields

---

.circleci/config.yml
shared/celery_router.py
shared/typings/oauth_token_types.py

python 3.7 is EOL and there are some 3.8 features we want to use. this PR removes 3.7 from CI as well as 3.7 compat things that i found via grep. tests pass

chore: remove python 3.7 from CI and some >=3.7-specific code

---

setup.py
shared/rollouts/__init__.py
shared/rollouts/features.py
tests/unit/test_rollouts.py

this came up on slack yesterday and i thought it'd be fun to throw something together. let me know if you have any feedback or if we want to use a Real Product for this instead
notes:
- it can nominally support A/B tests, but our data isn't prepared to support analysis. mostly meant for simple rollouts at the moment
- increasing a rollout requires a code change and new deploy which is not ideal. an alternative could be to read the rollout proportions from redis and cache for, say, 4h,  if we have a good way to update values in production redis
- i used the 128-bit hash because it was there, but at our volumes we are probably safe from the birthday problem with 64 bits? i didn't crunch the numbers though, just going on vibes
- the bucketing logic uses floats with int truncation which a …

feat: create Feature class for handling feature rollouts

---

shared/analytics_tracking/events.py
tests/unit/test_analytics_tracking.py

since we're now sending events to Sentry's pubsub, we want to append all event names with codecov, to differentiate between codecov events and sentry's ones
You can see event names listed here https://l.codecov.dev/twR2yU 

prepend Codecov to event names 

---

shared/torngit/github.py

Instead of throwing error we're gonna pretend like it didn't happen.

chore: Handle gh refresh attempt failure more gracefully

---

shared/analytics_tracking/events.py
tests/unit/test_analytics_tracking.py

Renaming events based on data team request 

renaming events based on data team request

---

shared/torngit/github.py

https://github.com/codecov/internal-issues/issues/126
Not sure why errors like https://codecov.sentry.io/issues/3456622213/events/96297c785ddf4d3a8b74883c38e28670/ are happening sometimes.  Let's see if any of https://docs.github.com/en/apps/oauth-apps/maintaining-oauth-apps/troubleshooting-oauth-app-access-token-request-errors are the reason.

feat: Log info about errors when exchanging code for access token

---

shared/reports/editable.py
tests/unit/test_report.py

When processing reports (more than 1 per `UploadProcessor` task) it's possible
that we will merge a `Report` into a `EditableReport` (the original).
This is fine, but we were not respecting the fact that files inside
`EditableReport` should be `EditableReportFile`.
These changes force all files merged into an `EditableReport` to be
of type `EditableReportFile`. Merge is left unchanged, cause it seems
complex. Instead we just run an extra check and cast to `EditableReportFile`
if needed.
closes: codecov/internal-issues#nternal-issues#138
Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. In 2022 this entity acquired Codecov and as result Sentry is going to need some rights from me in order to utilize my …

fix: make sure EditableReport is merged with EditableReportFile

---

shared/validation/helpers.py

since newheader, newfooter and newfiles will be outdated names soon, we'll be using condensed_header, condensed_footer and condensed_files instead with keeping the old names valid for backward compatibility 

replacing newheader and newfooter with condensed_header and condensed_footer

---

setup.py
shared/github/__init__.py
tests/unit/test_github.py

We need the `get_github_integration_token` in `codecov-api`
No new code here - just pulled things from the following `worker` sources:
* https://github.com/codecov/worker/blob/main/services/github.py
* https://github.com/codecov/worker/blob/main/services/pem.py
* https://github.com/codecov/worker/blob/main/services/tests/test_github.py

ref: Include GitHub app token code from worker

---

shared/metrics/sentry.py
shared/reports/readonly.py
shared/reports/resources.py

some known-slow transactions in `codecov-api` have huge uninstrumented spans that we want more insight into. the spans are most likely in this range of code https://github.com/codecov/codecov-api/blob/8f09643371c38ef98c713ac3f504a0739e7101ec/services/report.py#L77-L95 where we process the raw chunks/files/sessions data in `shared`.
this PR adds sentry instrumentation to that code, but it doesn't add a dependency on sentry. if sentry is available we use its functions, otherwise we just stub them
`pytest` for `shared` works so the non-sentry path is not broken (assuming we have tests for report code...) and `pytest` + actual usage with a test sentry project show that it works when used in `codecov-api` and `worker`
Look, I get it. The entity doing business as "Sentry" was incorporated in …

perf: provide sentry tracing fns if available, else stub them

---

shared/reports/filtered.py
shared/reports/readonly.py
shared/reports/resources.py
tests/unit/reports/samples/test_filtered.py
tests/unit/reports/test_readonly.py
tests/unit/test_report.py

https://github.com/codecov/internal-issues/issues/155
sentry traces show `ReportPaths.single_directory()` in `codecov-api` takes a while. [definition](https://github.com/codecov/codecov-api/blob/8f1d7d5f723d24d06286b3cb656fc99d2b5204da/services/path.py#L214). it basically returns a flat list of directory/file objects with the name/totals, calling `report.get(path).totals` to get the totals which is more processing than necessary
this PR creates a more minimal way to get the totals in case that fixes things
Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. In 2022 this entity acquired Codecov and as result Sentry is going to need some rights from me in order to utilize my contributions in this PR. So here's …

perf: get_file_totals() to sidestep some extra processing

---

shared/reports/filtered.py
tests/unit/reports/samples/test_filtered.py

In Filtered Report, line modifiers can take a long time to compute, that's called by `lines` property. We will cache the computation so that when that property is called more than once it would return the cached value. This will speedup the public reports API endpoint as it currently references `lines` three separate times in its serializers.
Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. In 2022 this entity acquired Codecov and as result Sentry is going to need some rights from me in order to utilize my contributions in this PR. So here's the deal: I retain all rights, title and interest in and to my contributions, and by keeping this boilerplate intact I confirm that Sentry can use, modify, copy, and …

ref: Filtered Report to not recompute lines when already called (#729)

---

shared/torngit/base.py
shared/torngit/github.py
tests/unit/torngit/test_github.py

Add a short timeout to the GitHub education API we use to check if a user is student. This GH call is known to be flaky, causing timeouts when this is called during the login step. This change gives it 3s to respond before default to "not a student" like how it is being handled currently when there's other errors coming from this GH call.
Note that after this is released and API is using this package, we need to turn off the `student_disabled` config in API.
Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. In 2022 this entity acquired Codecov and as result Sentry is going to need some rights from me in order to utilize my contributions in this PR. So here's the deal: I retain all rights, title and interest …

fix: Timeout Github API student check (#277)

---

shared/github/__init__.py
tests/unit/test_github.py
tests/unit/torngit/test_github.py

Updating get github integration to use host override tech

---

shared/validation/install.py
tests/unit/validation/test_install_validation.py

[Instance-wide admins](https://docs.codecov.com/docs/configuration#instance-wide-admins) are needed to set up the self-hosted version of Codecov, but the schema validation fails as it currently does not allow `admins`.

Add admins to config schema

---

setup.py
shared/bundle_analysis/models.py
shared/torngit/github.py
shared/validation/user_schema.py
tests/integration/test_github.py

This PR includes a few changes:
* return PR labels from the GitHub pull request response (for use with https://github.com/codecov/engineering-team/issues/896)
- only needed for GitHub right now so I didn't implement similar functionality for other providers
* updates the `ai_pr_review` yaml schema (also to support https://github.com/codecov/engineering-team/issues/896)
* switch to SQLAlchemy 1.x so that we're compatible with `worker`

GitHub PR labels, SQLAlchemy version

---

.github/workflows/ci.yml
setup.py
shared/reports/resources.py
shared/torngit/base.py

Addresses https://github.com/codecov/engineering-team/issues/874

chore(ci): Add Python 3.12

---

shared/torngit/github.py
tests/integration/cassetes/test_github/TestGithubTestCase/test_get_pull_request_from_fork.yaml
tests/integration/test_github.py

context: codecov/engineering-team#736
To authenticate that a tokenless upload legitimely comes from a fork
we need to check the git provider. We also need the repo where the
PR originated.
These changes also add the "slug" to the PR info, so that we can
check that the HEAD is from the fork and the BASE is the target repo
of the upload.
Notice that currently the CLI only supports tokenless for Github,
so yeah I'm only adding this to github and not other providers, but
we need to add tokenless to the others anyway.
Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. In 2022 this entity acquired Codecov and as result Sentry is going to need some rights from me in order to utilize my contributions in this PR. So …

chore: Get origin repo of PRs

---

shared/bundle_analysis/__init__.py
shared/bundle_analysis/comparison.py
shared/bundle_analysis/models.py
shared/bundle_analysis/parser.py
shared/bundle_analysis/report.py
shared/bundle_analysis/storage.py
tests/samples/sample_bundle_stats.json
tests/samples/sample_bundle_stats_other.json
tests/unit/bundle_analysis/test_bundle_analysis.py
tests/unit/bundle_analysis/test_bundle_comparison.py

Support multiple bundles per bundle analysis report.  A bundle is a high level thing that might exist in a monorepo (i.e. something like "dashboard" or "admin" etc.).  A single session/upload contains information pertaining to a single bundle.  See the schema changes in `models.py` for a more detailed understanding of the relationships.

feat: Support multiple bundles per bundle analysis report

---

shared/celery_config.py
shared/reports/enums.py
shared/utils/enums.py

Create upload test tasks

---

shared/torngit/github.py

I learned from https://github.com/codecov/codecov-cli/pull/342/commits/f4b31f18ed231b37a74e9bec71d710bc412a5492 that the head->repo value might be null.
Indeed in [the docs](https://docs.github.com/en/rest/pulls/pulls?apiVersion=2022-11-28#get-a-pull-request), the schema (terribly hard to look in that little window) does state that it can be null.
```
"head": {
"type": "object",
"properties": {
[...]
"repo": {
"type": [
"object",
"null"
],
```
These changes mimic the ones in the linked commit, making it so that
we don't raise an exception if the repo info is null.
Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. In 2022 this entity acquired Codecov and as result Sentry is going to need some rights from me …

fix: handle if head->repo is None

---

shared/bundle_analysis/storage.py

Was seeing the default being used in staging even though we have a config var set for this.  Not sure if there's some kind of race condition at module initialization time.
Also added the upload storage path (which is currently specified in the API).

Lazy load bundle analysis bucket name

---

shared/validation/user_schema.py
tests/unit/validation/test_validation.py

We want to support longer flag names up to 1024 characters. We also want to support special characters other than single and double quotes.

feat: flag names are longer and contain special chars

---

shared/bundle_analysis/report.py

Fix bundle total_size function, in the query forgot a join with Asset and Session models, so it was retrieving all Assets in the DB

fix: bundle total size not calculated correctly (#1021)

---

shared/bundle_analysis/models.py
shared/bundle_analysis/parser.py
tests/unit/bundle_analysis/test_bundle_analysis.py

- Allow parsing of multiple uploads where there's duplicate chunk IDs between uploads
- Allow re-uploading a bundle file where it has the same bundle name, the previous upload will be fully replaced by the current one
https://github.com/codecov/engineering-team/issues/1079
https://github.com/codecov/engineering-team/issues/1080
Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. In 2022 this entity acquired Codecov and as result Sentry is going to need some rights from me in order to utilize my contributions in this PR. So here's the deal: I retain all rights, title and interest in and to my contributions, and by keeping this boilerplate intact I confirm that Sentry can use, modify, copy, and redistribute my …

feat: Fix bundle analysis DB model and upload parsing

---

shared/bundle_analysis/parser.py
shared/bundle_analysis/report.py
tests/samples/sample_bundle_stats_no_assets.json
tests/samples/sample_bundle_stats_no_chunks.json
tests/samples/sample_bundle_stats_no_modules.json
tests/unit/bundle_analysis/test_bundle_analysis.py

When assets is empty -> no asset reports and 0 total size for the bundle
When chunks is empty -> no associations with assets nor modules
When modules is empty -> no associations with chunks
Also saves bundle stats file info into the report.

feat: handle bundle reports with empty assets/chunks/modules

---

shared/storage/gcp.py
tests/unit/storage/test_gcp.py

context: codecov/engineering-team#1029
As suggested in the ticket we want to explore if switching the checksum
validation to 'crc32c' (from 'md5') reduces the occurance of
`DataCorruption` errors.
I switched the function to `download_as_bytes` (see [docs](https://cloud.google.com/python/docs/reference/storage/latest/google.cloud.storage.blob.Blob#google_cloud_storage_blob_Blob_download_as_bytes)) because the existing `download_as_string` is
deprecated and doesn't provide the `cheksum` argument.
I also added a retry mechanism to retry the download once in case
of `DataCorruption`. This is based on vibes and feelings mostly,
but my line of thought is that this _might_ be a temporary issue
around some part of the system downloading a file and another part
updating it kinda concurrently. Also …

change checksum of gcp download. add retry.

---

shared/bundle_analysis/parser.py
tests/samples/sample_bundle_stats_decimal_size.json
tests/unit/bundle_analysis/test_bundle_analysis.py

Handle decimal values in size
https://github.com/codecov/engineering-team/issues/1140

fix: Cast bundle stats size to int

---

shared/celery_config.py
shared/utils/enums.py
tests/unit/test_celery_config.py

We're adding a task to save_commit_measurements as right now is embedded to the upload_finisher task and we want it to work in isolation. 

feat: add task name to save commit measurements

---

shared/torngit/github.py
tests/integration/cassetes/test_github/TestGithubTestCase/test_get_repos_from_nodeids_generator.yaml
tests/integration/test_github.py
tests/unit/torngit/test_github.py

context: codecov/engineering-team#971
Adds function to get repositories from Github's GraphQL api.
It uses node_id to get the specified node from gh. This can be found in
the INSTALLATION webhook that we will process.
Along with it there will be the databaseId (service_id).
Adding the `expected_owner` entry because when processing an installation webhook
we do know what the expected owner is. Fetching the owner would require another request,
but can be done (again by node_id)
The idea is to use this function when syncing repos if we know what the repos
covered by an installation are.

feat: get repos from graphql

---

shared/bundle_analysis/report.py
shared/bundle_analysis/storage.py

Add a context manager for opening and closing DB sessions around queries in `AssetReport` and `BundleReport`. This way when the session in `BundleAnalysisReport` is closed, it won't make its children reports' session closed. This is needed in API when `BundleAnalysisReport` is resolved and cleaned up (ie DB session closed), but subsequent resolves to `AssetReport` and `BundleReport` will fail due to the shared DB session. This makes sure each `*Report` can manage its own DB session.
Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. In 2022 this entity acquired Codecov and as result Sentry is going to need some rights from me in order to utilize my contributions in this PR. So here's the deal: I retain all …

Bundle analysis: auto open and close DB session

---

shared/rollouts/__init__.py
tests/unit/test_rollouts.py

Don't let `Feature` make requests to database unless `check_value()` is called. This will help our tests in worker because they don't have access to django db unless we explicitly give it.

perf: don't fetch from db in constructor

---

shared/validation/install.py
tests/unit/validation/test_install_validation.py

context: codecov/engineering-team#1243
Adds a `guest_access` bool config option for the install yaml.
Apparently this is a documented legacy setting that we want to bring back.

feat: add 'guest_access' option to install config

---

shared/torngit/github.py
tests/unit/torngit/test_github.py

Github will possibly return a 429 status code if the rate limit is reached per:
https://docs.github.com/en/rest/using-the-rest-api/rate-limits-for-the-rest-api?apiVersion=2022-11-28#exceeding-the-rate-limit

Handle 429 status code in torngit as Rate limit error

---

shared/rollouts/__init__.py
tests/unit/test_rollouts.py

The `salt` and `proportion` parameters in `Feature` are only ever used to create a new feature flag. If a feature flag with the same name already exists in the database, then the parameters are ignored. 
This can be confusing as the params don't actually represent the values the feature flag is using 99% of the time. Its more safe to just always create feature flags with the default values (proportion=0, salt=`randomlygeneratedstring`) and we can modify them via django admin later. 
Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. In 2022 this entity acquired Codecov and as result Sentry is going to need some rights from me in order to utilize my contributions in this PR. So here's the deal: I retain all …

refactor: remove proportion and salt params from Feature

---

shared/bundle_analysis/models.py
shared/bundle_analysis/report.py

- Create a custom context manager for SQLAlchemy session because worker is currently stuck on SQLAlchemy version <1.4, and built in context manager for session is introduced in 1.4 (which is also what codecov-api uses).
- It is a lot of work to upgrade worker's SQLAlchemy version because it is too closely tied into its postgres DB support. 
When worker fully migrates to Django for postgres, we can simply upgrade the SQLAlchemy version to support modern functionalities and delete this legacy code.
- For now if the SQLAlchemy version is <1.4 it will go through the custom LegacySessionManager context manager object to handle opening and closing its sessions.
Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. In …

Bundle Analysis: Create DB session manager for legacy SQLAlchemy versions

---

setup.py

Without an upper limit here on django versioning, it goes to latest release, `5.x`, which is incompatible with python `3.9`, the version `api` uses. Out of an abundance of caution, let's keep these two projects on the same major version, which has the security patch for the [target vuln](https://github.com/advisories/GHSA-xxj9-f6rv-m3x4)

upper limit on django version

---

shared/bundle_analysis/__init__.py
shared/bundle_analysis/parser.py
tests/unit/bundle_analysis/test_bundle_analysis.py

Inject the plugin name (the plugin that was responsible for creating the stats file) if parsing the bundle stats file fails, this will be later used by the worker's BA processor to surface the bad plugin name as Sentry metrics.

Bundle Analysis: surface plugin name on parser error

---

shared/bundle_analysis/models.py
shared/validation/helpers.py
tests/unit/validation/test_helpers.py
tests/unit/validation/test_install_validation.py
tests/unit/validation/test_validation.py
tests/unit/yaml/test_user_yaml_validation.py

Glob patterns were always considered as "prefixes",
and would match any depth after their ending.
Recently this became an issue noticed by a customer that was
trying to ignore all files ending with `bundle`, but ended up having
more files than intended ignored.
These changes remove this "glob is always a prefix" idea and solve this
use case. Users can still use "path as a prefix" but only proper paths,
not globs. They can also use regexes.
Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. In 2022 this entity acquired Codecov and as result Sentry is going to need some rights from me in order to utilize my contributions in this PR. So here's the deal: I retain all rights, title and interest in and to my …

fix: fix glob pattern translation

---

shared/config/__init__.py
shared/yaml/user_yaml.py
tests/unit/yaml/test_user_yaml.py

These changes alter the default site behavior to be default centric
_after_ `PATCH_CENTRIC_DEFAULT_TIME_START` (set to 2024-04-30).
In addition this new default is only selected for owners that have
an onboarding date (`Owner.created_at`) _after_ `PATCH_CENTRIC_DEFAULT_TIME_START`.
This is done to prevent breaking customers that might be currently relying
on the default `project` status to gatekeep PRs.
In the interest of keeping experiences consistent for an existing customer we are
also making this change per-owner (not per-repo).
context: https://github.com/codecov/engineering-team/issues/1387
Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. In 2022 this entity acquired Codecov and as result Sentry is …

feat: make default behavior patch-centric

---

shared/rollouts/__init__.py
tests/unit/test_rollouts.py

Updates the async version of `check_value()` so that it matches the non-async version.

chore: update async interface

---

shared/storage/minio.py
tests/unit/storage/test_minio.py

this allows us to specify the region correctly so various scopes and other aspects don't default to us-east-1 internally

feat: support minio region passing to client

---

shared/torngit/github.py

Adding some logging for the fetch_page functions in github.py for logging the repo names when returned from the api call

chore: add repo logs when fetching GH repos

---

shared/torngit/github.py

Small update to the logs to also log if the token is the same as the self.token

chore: also log isSameToken

---

shared/rollouts/__init__.py
tests/unit/test_rollouts.py

Should close https://github.com/codecov/engineering-team/issues/1515. Refactors the bucketing logic so that users' assignments to variants never change even when the total rollout proportions change.
Added a test for this case specifically

fix: fix feature bucketing logic

---

shared/rollouts/__init__.py
tests/unit/test_rollouts.py

Force `.check_value()` interface for feature to accept kwargs so we don't forget to explicitly state which identifier type we're using (repoid vs ownerid)
Sentry/Codecov employees and contractors can delete or ignore the following.
-->

fix: force kwargs for feature

---

shared/rollouts/__init__.py
tests/unit/test_rollouts.py

- if the `CODECOV__FEATURE__DISABLE` env var is set, return default values without bothering to look in the db for feature configuration
- if `CODECOV__FEATURE__{name.upper()}` is set, return the value it is set to for the experiment with that name
self-hosted users or users on dedicated enterprise instances may want to turn some of these knobs but may not want to use (or have access to) the Django Admin UI for configuring feature variants
https://github.com/codecov/worker/pull/373 is the experiment that we want this for initially. at least one environment is interested in raising this value without waiting on us to follow through on a whole experiment + cleanup to get whatever we decide
Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in …

feat: allow environment vars to disable/override Feature values

---

shared/torngit/github.py

Use jwt instead of self.token

---

shared/reports/enums.py
shared/torngit/github.py
tests/unit/reports/test_enums.py

Remove the `PARALLEL_PROCESSED` enum because it currently is not used. It will be used when parallel upload processing is fully rolled out.
There's no need to make the migration for it right now if it's not going to be used. (migration hasn't been made yet)
Sentry/Codecov employees and contractors can delete or ignore the following.
-->
Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. In 2022 this entity acquired Codecov and as result Sentry is going to need some rights from me in order to utilize my contributions in this PR. So here's the deal: I retain all rights, title and interest in and to my contributions, and by keeping this boilerplate intact I confirm that Sentry can use, modify, copy, and …

fix: remove parallel_processed enum

---

docker-compose.yml

instead of starting a container and running `sleep 86400` to keep it from shutting down, we can set `tty: true`

[chore] switch from `sleep 86400` to a tty service

---

shared/torngit/github.py
tests/unit/torngit/test_github.py

Create simple fallback system to retry requests if we have more tokens available
and the current one just hit a limit error.
Notice that the `TorngitBaseAdapter` holds on to whatever kwargs you give it
inside `data` [[1](https://github.com/codecov/shared/blob/b2798abaa2b47d8834cf7d552cc892efbff01b70/shared/torngit/base.py#L97)] property,
so we just need to pass more tokens to the `Github` instance.
Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. In 2022 this entity acquired Codecov and as result Sentry is going to need some rights from me in order to utilize my contributions in this PR. So here's the deal: I retain all rights, title and interest in and to my contributions, and by keeping this boilerplate …

feat: fallback system for gh requests

---

shared/django_apps/reports/migrations/0016_testresultreporttotals_error.py
shared/django_apps/reports/migrations/0017_testinstance_flaky_status.py
shared/django_apps/reports/models.py
shared/github/__init__.py
shared/torngit/base.py
shared/torngit/github.py
tests/unit/test_github.py
tests/unit/torngit/test_base.py
tests/unit/torngit/test_github.py

Part of https://github.com/codecov/engineering-team/issues/1167, this is for Github calls, the other git providers will be added next.
We want to know who's making all these calls! So I added some Counters.
This is a first implementation - the strategy I picked was to increment the Counter before the code makes the request to github - it uses a helper function and technically could error out somewhere along the way before it actually makes the call. So you could argue that the Counters are counting intended requests, but hopefully errors between intent-to-call-github and actually making the outgoing request are low, and if not, at least they are logged.
The counts are named for the functions that call them, so we can trace a`Counter` back to the place in our code where it is being called. …

Add count_and_get_url_template to github handler

---

shared/celery_config.py
tests/unit/test_celery_config.py

- add the test results tasks to the task routes in the celery config so we can configure which queue those tasks are routed to from the config
- defines the upload finisher task name in celery_config.py so we can have it defined in one place and use it in the worker
Fixes: https://github.com/codecov/engineering-team/issues/1538

feat: add test results config group to celery config

---

shared/django_apps/codecov_auth/models.py
tests/unit/django_apps/codecov_auth/test_codecov_auth_models.py

in a few occasions we had in staging (and 1 cloud customer) scenarios that
lead us to believe that the default app_id at times might not be present for the api pods
config.
The bad side_effect is that installations change name to 'unconfigured_app' and that's
only manually reversible. To prevent the app from destroying itself if the default
app id is not present we assume apps are configured in this scenario.
Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. In 2022 this entity acquired Codecov and as result Sentry is going to need some rights from me in order to utilize my contributions in this PR. So here's the deal: I retain all rights, title and interest in and to my contributions, and by keeping this …

feat: prevent the app from destroying itself

---

shared/config/__init__.py
tests/unit/yaml/test_user_yaml.py

aka "the missing Z"
I wrongfully assumed that `fromisoformat` would generate a timezone aware datetime.
This is an issue because we generate those from the worker and api (that is, the
createstamp of owners saved in the database is pulled as being timezone aware)
And you can't compare timezone-aware and timezone-naive datetimes :clown:
So this errors out and it's pretty critical.
Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. In 2022 this entity acquired Codecov and as result Sentry is going to need some rights from me in order to utilize my contributions in this PR. So here's the deal: I retain all rights, title and interest in and to my contributions, and by keeping this boilerplate intact I confirm …

fix: make patch cuttoff date timezone aware

---

shared/github/__init__.py
shared/torngit/base.py
shared/torngit/github.py
shared/typings/oauth_token_types.py
tests/unit/test_github.py
tests/unit/torngit/test_github.py

These changes improve the github token fallback system by:
1. Updating the instance's `self._token` to be a not-rate-limited one,
so that if the instance make subsequent requests they won't be immediately
rate limited and have to go through the fallback process again
2. Propagates to other parts of the system that a given installation is rate limited.
This is done via redis (apparently shared can access redis now)
Sadly the function that fallsbakc if other tokens are available is full of
side effects, as documented.
Also did a small refactor in the code aggregating the primary and secondary rate limit errors.
Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. In 2022 this entity acquired Codecov and as …

feat: improve fallback system

---

shared/github/__init__.py
shared/torngit/github.py
shared/torngit/github_enterprise.py
tests/unit/test_github.py
tests/unit/torngit/test_github.py
tests/unit/torngit/test_github_enterprise.py

Part of https://github.com/codecov/engineering-team/issues/1167, this is for Github Enterprise calls, the other git providers will be added next.
Technically right now we are counting GithubEnterprise calls, but they are incrementing the `Counter` for Github calls! Added a system by which our Github and GithubE handlers can share urls without sharing counters.

Add count_and_get_url_template to github enterprise handler

---

shared/github/__init__.py
shared/torngit/base.py
shared/torngit/github.py
shared/typings/oauth_token_types.py
shared/typings/torngit.py
tests/unit/test_github.py
tests/unit/torngit/test_github.py

There's an integration issue with the fallback system: the worker is passing the extra installation info in `data.fallback_installations` not `data.fallback_tokens`.
Personally I think that `fallback_installations` makes more sense here.
To prevent this silly (totally my fault for not testing properly locally) issue from happening again I added typehints to the `data` of TorngitBaseAdapters.
One more issue is that what's being passed as `installation_id` (that is marked as rate-limited)is the integration_id (as GitHub passes down to us), not the GithubAppInstallation instance ID.
Because it's possible to have installations from different apps we need to pass the `app_id` as well.
Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as …

fix: fix fallback system for GH

---

shared/github/__init__.py
shared/typings/torngit.py

undo notation only available from pyhon 3.10 because api is still in 3.9

---

shared/bundle_analysis/parser.py

We were originally doing inserts every time we created an Asset, Chunk, or Module object. Now we are doing the inserts into the DB after having created them all.
Fixes: https://github.com/codecov/internal-issues/issues/399

fix: do bulk inserts in bundle analysis parser

---

tests/requirements.txt

This mitigates [GHSA-jjg7-2v4v-x38h](https://github.com/advisories/GHSA-jjg7-2v4v-x38h) vulnerability.
I ran `pip-compile --upgrade-package idna` to generate this. The dependencies also don't pin the exact version, and 3.7 is within the ranges of downstream dependencies.
Since this is an update to the test, this is safe for release (but doesn't require a separate release, as I'm not adding any features).
Link to ticket: https://github.com/codecov/internal-issues/issues/415
Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. In 2022 this entity acquired Codecov and as result Sentry is going to need some rights from me in order to utilize my contributions in this PR. So here's the deal: I retain all rights, …

Update `idna` package to 3.7

---

shared/rollouts/feature_flags_experiments.sql

Originally this SQL lived in the metabase dashboard, so I'm checking it into git so that we can track it. The code that get executed on Metabase still lives in Metabase though, but I don't think there's a solution here (atleast a solution worth investigating)

check-in experiment SQL to git

---

shared/github/__init__.py
shared/torngit/github.py
tests/unit/test_github.py

fixes issue https://l.codecov.dev/OGL5z9
It's possible that an installation is still rate limited but for a very
short period of time (less than 1 second). In this case we'd attemp to
set it as rate limited with a TTL of 0.
That causes a `RedisError`

fix: Don't rate limit installation for 0 seconds

---

shared/bundle_analysis/storage.py
shared/storage/exceptions.py
tests/unit/bundle_analysis/test_bundle_analysis.py

1 of 2 PRs of the fix.
When encountering a rate limit error by GCS when doing save file to the BA bucket, instead of failing the processor step completely, it will now retry.
GCS has a 1 PUT request per second rate limit when updating an existing object in storage, the BA processor may encounter this edge case when multiple BA processing tasks are running in parallel to update multiple bundle stats files. And when this is encountered, we don't update the SQLite file for this stats file therefore causing incorrect data. This fix will retry the task after a short 20s cooldown to once again attempt to upload, at this time most likely the rate limit threshold would be passed. Note that there can still be cases when multiple retried tasks run at the same time again, but the probability of this …

bundle analysis catch rate limit error

---

.gitignore
shared/reports/resources.py
shared/reports/types.py
shared/yaml/user_yaml.py

Just a few minor changes to improve the code quality:
* fix the type annotation of `coverage` on `ReportTotals` and add comment
* refactored `_process_totals` to be more readable 
* add type annotations to `UserYaml.get_final_yaml`
None of these changes should result in functional differences. 
Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. In 2022 this entity acquired Codecov and as result Sentry is going to need some rights from me in order to utilize my contributions in this PR. So here's the deal: I retain all rights, title and interest in and to my contributions, and by keeping this boilerplate intact I confirm that Sentry can use, modify, copy, and redistribute my contributions, under Sentry's …

Add type annotations and other improvements

---

.github/workflows/ci.yml

Similar to https://github.com/codecov/codecov-api/pull/556, from https://github.com/codecov/gha-workflows/pull/23, updating deprecated GHAs

dev: update gha-workflows to latest version

---

ruff.toml

fix expected python version for ruff

---

shared/torngit/github.py
tests/integration/test_github.py

fixes a sentry issue https://l.codecov.dev/I8iSfU
we upsert a repo with `branch=None` due to this default value. that violates the nonnull constraint on that field
other places in the same file default to "master" as well: [one](https://github.com/codecov/shared/blob/5ada529179d25063f02e64be0a9cba3129d8d5d6/shared/torngit/github.py#L1175) and [two](https://github.com/codecov/shared/blob/5ada529179d25063f02e64be0a9cba3129d8d5d6/shared/torngit/github.py#L1159)

fix: default branch to "master" in torngit github

---

shared/bundle_analysis/comparison.py
shared/validation/user_schema.py
tests/unit/bundle_analysis/test_bundle_comparison.py

- add `require_bundle_changes` on codecov yml
- add `total_size_delta` property for BA comparisons for ease + test

add require_bundle_changes to yaml

---

ruff.toml
shared/analytics_tracking/__init__.py
shared/django_apps/codecov_auth/helpers.py
shared/django_apps/dummy_settings.py
shared/django_apps/legacy_migrations/management/commands/migrate.py
shared/helpers/yaml.py
shared/reports/filtered.py
shared/reports/resources.py
shared/reports/types.py
shared/rollouts/__init__.py
shared/torngit/gitlab.py
shared/utils/merge.py
shared/utils/migrate.py
shared/utils/totals.py
tests/unit/bundle_analysis/test_bundle_analysis.py
tests/unit/utils/test_flare.py
tests/unit/utils/test_merge.py

Part of the lint enhancement epic, this PR aims to add the Pycodestyle error rules, and the Pylint Convention and Pylint Error rules.
These can be found here:
- https://docs.astral.sh/ruff/rules/#error-e
- https://docs.astral.sh/ruff/rules/#error-e_1
- https://docs.astral.sh/ruff/rules/#convention-c
A majority of the fixes were related to E721 (isinstance comparisons), E722 (bare except) and E713 (test for membership should be not in)
There were also one for PLE0605 and one for PLE1205
Closes https://github.com/codecov/engineering-team/issues/1845
This PR adds the rules listed above and fixes any errors that stemmed from them.
Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. In 2022 this entity acquired …

dev: Add most E, all PLC and PLE ruff rules

---

shared/analytics_tracking/pubsub.py
tests/unit/analytics_tracking/test_analytics_tracking.py

We've had quite a few issues on sentry due to `json.dumps()` not being able to recognize datetime objects. 

[fix] Fix analytics tracking datetime serialization issue 

---

shared/github/__init__.py
tests/unit/test_github.py

Investigating `RepoWithoutValidBotError` I discovered that about 1/3 of the errors come from `InvalidInstallationError`. This means we tried to get an `access_token` for a GitHub app but failed to do so.
I know that part of these errors (part of "permission_error") is from suspended apps. We don't track what installations are suspended, but we can't use them anymore (that is what being suspended means). Part of the errors come from that. Why would a used suspend Codecov and keep uploading? God knows. Maybe they just forgot to change the CI.
The other part ("installation_not_found") I suspect are actually deleted installations that we did not delete for some reason.
In any case I think that having this extra info would be helpful when debugging issues with GitHub apps. It also opens the …

track why we fail to get integration tokens

---

shared/bundle_analysis/report.py
tests/samples/asset_link_curr_a.json
tests/samples/asset_link_curr_b.json
tests/samples/asset_link_prev_a.json
tests/samples/asset_link_prev_b.json
tests/unit/bundle_analysis/test_asset_association.py

Asset name changes from one bundler build to another across commits, therefore we don't know if the current asset is a new one or a continuation of the previous one. This PR adds a function to offer a heuristic to associate the current asset to an asset from the previous commit.
The rules are that if the hashed asset name exists in the previous bundle report then this is considered the same asset. Similarly if all the modules of the asset are the same as any in the previous bundle report it is also considered the same asset. We track assets through a generated UUID, when 2 assets are considered associated then they will have the same UUID.
This mechanism is important for providing analytics asset size trends throughout the course of its existence. This component will be implemented in the …

Bundle Analysis: associate past assets to current parsed bundle

---

shared/rollouts/features.py
shared/torngit/github.py
tests/integration/test_github.py
tests/unit/torngit/test_github.py

https://github.com/codecov/engineering-team/issues/1757
[github docs on timeouts](https://docs.github.com/en/rest/using-the-rest-api/troubleshooting-the-rest-api?apiVersion=2022-11-28#timeouts):
> If GitHub takes more than 10 seconds to process an API request, GitHub will terminate the request and you will receive a timeout response and a "Server Error" message.
> ...
> For example, if you are requesting 100 items on a page, you can try requesting fewer items.
`list_repos()` and family use a page size of 100, and we sometimes observe 502s/504s in response after 10 seconds which is github's cutoff. this PR sets up an experiment to test smaller page sizes
this should be running with a user oauth token that has its own rate limit. so this should probably not cause rate limit issues

torngit github: set up experiment for list_repos page size

---

shared/torngit/github.py

https://github.com/codecov/engineering-team/issues/1757
we sometimes observe 502s and 504s in `list_repos()`. https://github.com/codecov/shared/pull/232 attempts to mitigate that by testing a smaller page size, but also sometimes retrying 502/503/504 will just work

torngit github: retry on 502/503/504

---

shared/torngit/base.py
shared/typings/oauth_token_types.py
shared/validation/install.py
tests/unit/validation/test_install_validation.py

Before started working on the revamping app usage I took some time to access what we currently have.
This ended up manifesting in type annotations and a small cleanup in the install docs.
The only real addition is `services.github.dedicated_apps` config values for the
dedicated apps.
Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. In 2022 this entity acquired Codecov and as result Sentry is going to need some rights from me in order to utilize my contributions in this PR. So here's the deal: I retain all rights, title and interest in and to my contributions, and by keeping this boilerplate intact I confirm that Sentry can use, modify, copy, and redistribute my contributions, under Sentry's choice of …

chore: typehints + comments

---

shared/torngit/base.py
shared/torngit/github.py
tests/unit/torngit/test_github.py

I broke the GH fallback system again 😅
Fixes this issue: https://l.codecov.dev/dEsZeK
The problem is that since https://github.com/codecov/shared/pull/225
(technically https://github.com/codecov/worker/pull/470 actually) we include 1 extra piece of information in `GitHubAppInstallationInfo`, the `GitHubAppInstallation.id`.
This is breaking the function that gets tokens because we are destructuring the info dict
into the kwargs for the function (with the extra, unexpected `id` one).
To fix that we just pop it before calling the function.
Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. In 2022 this entity acquired Codecov and as result Sentry is going to need some rights from me in order to utilize my …

fix: fix fallback system in GH (again)

---

ruff.toml
shared/django_apps/utils/model_utils.py
shared/helpers/cache.py
shared/reports/api_report_service.py
shared/reports/editable.py
shared/reports/filtered.py
shared/reports/resources.py
shared/storage/memory.py
shared/torngit/base.py
shared/torngit/bitbucket.py
shared/torngit/github.py
shared/torngit/gitlab.py
shared/yaml/user_yaml.py

Part of the lint enhancement epic, this PR aims to add the PerfLint PERF rules.
These can be found here:
- https://docs.astral.sh/ruff/rules/#perflint-perf
All of the fixes were either doing list comprehensions where possible, or using .values() or .keys() when we only needed one or the other. The latter is definitely a micro-optimization, but it improves the clarity of the code as well.
Resources:
- Why list comprehensions are much faster in python 3.12: https://peps.python.org/pep-0709/
Closes https://github.com/codecov/engineering-team/issues/1931
This PR adds the rules listed above and fixes any errors that stemmed from them.
Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. In 2022 this entity acquired …

dev: Add perf rules for ruff on shared

---

shared/bundle_analysis/report.py
tests/samples/sample_bundle_stats.json
tests/unit/bundle_analysis/test_bundle_analysis.py

Update a bundle report's `assets` and `total_size` that allows the follow 3 filter options:
- the asset has at least one chunk whose `entry` value is the request boolean
- the asset has at least one chunk whose `initial` value is the request boolean
- the asset belongs to one of the request `asset_type`s
This filtering applies a intersection search, eg if all 3 are selected, all 3 clauses must be true.
closes https://github.com/codecov/engineering-team/issues/1924
closes https://github.com/codecov/engineering-team/issues/1897
Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. In 2022 this entity acquired Codecov and as result Sentry is going to need some rights from me in order to utilize my contributions in …

Allow filtering of bundle's assets

---

shared/django_apps/codecov_metrics/service/codecov_metrics.py

Also check that the payload is the same before skipping the write. Current tests should catch this logic already. 

Fix duplicate check in metrics service

---

setup.py
shared/validation/helpers.py
shared/validation/types.py
shared/validation/user_schema.py
shared/validation/validator.py
tests/unit/validation/test_helpers.py
tests/unit/validation/test_install_validation.py
tests/unit/validation/test_validation.py

We are extending the configuration for required_changes.
ticket: https://github.com/codecov/engineering-team/issues/1966
I might have overengineered the different conditions, but being able to combine in both AND and OR
operations is somewhat tricky. In the end it's a satisfaction problem in that all the elements in the
conditions list need to be satisfied for the comment to occur, and the elements themselves express
and OR grouping.

feat: extend configuration for `comment.required_changes`

---

shared/config/__init__.py
tests/unit/validation/test_validation.py
tests/unit/yaml/test_user_yaml.py

We tripped over this once already (fix [here](https://github.com/codecov/worker/pull/533)) - if we add it here it could save us from making the same mistake in the future.
This config is in our docs as defaulting to `True` so I don't see an issue with explicitly declaring it in the default configs.

add wait_for_ci to default site config

---

shared/validation/helpers.py
shared/validation/user_schema.py
shared/validation/validator.py
tests/unit/validation/test_helpers.py
tests/unit/validation/test_validation.py

These changes improve documentation (and add unit tests) to `comment.require_bundle_changes`
and adds a new config key `bundle_change_threshold`.
The new key is a threshold size for the bundle in bytes. The input value
is preferably a string that accepts certain size extensions (kb, mb, gb, ...) and is
coerced into a size in bytes (as an integer)
closes: https://github.com/codecov/engineering-team/issues/2018
Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. In 2022 this entity acquired Codecov and as result Sentry is going to need some rights from me in order to utilize my contributions in this PR. So here's the deal: I retain all rights, title and interest in and to my contributions, and by keeping this …

feat: bundle analysis comment threshold

---

shared/django_apps/codecov_auth/models.py
shared/torngit/gitlab.py
tests/unit/django_apps/codecov_auth/test_codecov_auth_models.py

This adds the feature to add and remove users from an account if the organization that is connected to the account is activating and deactivating users. We want to make sure that users who are deactivated are only removed when they are not associated with _any_ other organization that the account is associated with.
ref: https://github.com/codecov/engineering-team/issues/1993
Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. In 2022 this entity acquired Codecov and as result Sentry is going to need some rights from me in order to utilize my contributions in this PR. So here's the deal: I retain all rights, title and interest in and to my contributions, and by keeping this boilerplate intact I confirm that …

Sync Account Users when Activating/Deactivating Users

---

ruff.toml
shared/utils/test_utils/__init__.py
tests/integration/test_bitbucket.py
tests/integration/test_bitbucket_server.py
tests/unit/bundle_analysis/test_asset_association.py
tests/unit/bundle_analysis/test_bundle_comparison.py
tests/unit/django_apps/test_db_routers.py
tests/unit/github/test_github_installation_helpers.py
tests/unit/helpers/test_cache.py
tests/unit/reports/test_types.py
tests/unit/storage/test_minio.py
tests/unit/test_report.py
tests/unit/test_report_file.py
tests/unit/torngit/test_exceptions.py
tests/unit/validation/test_helpers.py
tests/unit/validation/test_install_validation.py
tests/unit/validation/test_validation.py

Forgot to turn back on the unused import rule for Ruff on shared. This does that and fixes any errors

dev: Unused import rule ruff

---

shared/celery_config.py
shared/django_apps/codecov_auth/models.py
shared/django_apps/codecov_auth/tests/factories.py
shared/utils/enums.py
tests/unit/django_apps/codecov_auth/test_codecov_auth_models.py
tests/unit/test_celery_config.py

* Adds some methods to check that a user can be added to an account. It replicates the logic in owners. 
* Adds task boilerplate for the activate account user task
This PR blocks: https://github.com/codecov/worker/pull/556
ticket ref: https://github.com/codecov/engineering-team/issues/1993
Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. In 2022 this entity acquired Codecov and as result Sentry is going to need some rights from me in order to utilize my contributions in this PR. So here's the deal: I retain all rights, title and interest in and to my contributions, and by keeping this boilerplate intact I confirm that Sentry can use, modify, copy, and redistribute my contributions, under Sentry's choice of …

Checks for Adding User to Account

---

shared/validation/helpers.py
shared/validation/types.py
tests/unit/validation/test_helpers.py

ticket: https://github.com/codecov/engineering-team/issues/2004
The bundle threshold needs to also accept percentages.
To do that we are going to re-use the percentage schema field and the
byte size schema field, and just have a wrapper around them.
A new return type has been created to make the difference between
absolute and percentage values more explicit (although technically
the values are different - float vs int - it will be easier to distinguish
if we have the type explicitly

feat: bundle threshold coercion

---

shared/bundle_analysis/parsers/v1.py
shared/bundle_analysis/parsers/v2.py
shared/bundle_analysis/report.py

Now that we have a field identifying whether a bundle is cached or not we need to set the value to false when processing a new upload.

bundle analysis: change parsed bundle to not cached

---

shared/torngit/bitbucket.py
tests/integration/cassetes/test_bitbucket/TestBitbucketTestCase/test_get_is_admin.yaml
tests/integration/cassetes/test_bitbucket/TestBitbucketTestCase/test_get_is_admin_not_admin.yaml

The `uuid` does not support filtering the bitbucket api. Here we filter manually after we retrieve the result to check if the user is an admin. 

[FIx] Update is admin API call for bitbucket

---

shared/rollouts/features.py
shared/validation/user_schema.py
shared/validation/validator.py
tests/unit/validation/test_validation.py

extends the user_schema config with the bundle_status entries.
It requires a feature flag not for any experiment, but to gate the release
of the coercion in bundle_threshold. The change is not forwards compatible,
so in the middle of deploying it's possible that old deploys would break
if the yaml was parsed by new deploys.
After a full rollout the value can be turned to True and the feature flag removed.
closes https://github.com/codecov/shared/pull/287

feat: bundle status config

---

shared/django_apps/core/managers.py
tests/unit/django_apps/core/test_manager.py

This filters out the repos that require Okta authentication and the user is not authenticated. This is to be used in API to filter out repos that users should not see.
ref: https://github.com/codecov/engineering-team/issues/1992

Add a filter for repos that requires Okta authentication

---

setup.py

This library was causing some `distutils` issues, so unpinning this so that we can install a more recent version if necessary.

Unpin django-models-utils

---

shared/django_apps/codecov_auth/models.py
tests/unit/django_apps/codecov_auth/test_codecov_auth_models.py

Currently the deactivation code is attempting to remove the incorrect owner reference (the org) when it's supposed to remove the user. This fixes it to remove the correct owner.

Fix deactivation of users on accounts

---

shared/django_apps/codecov_auth/models.py
tests/unit/django_apps/codecov_auth/test_codecov_auth_models.py

There is a bug where the number of activated users count is higher than expected because it is counting _all_ the owners for all users associated with an account. Since a user may have multiple owners, it is counting them all separately. This should now count only the number of users.
Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. In 2022 this entity acquired Codecov and as result Sentry is going to need some rights from me in order to utilize my contributions in this PR. So here's the deal: I retain all rights, title and interest in and to my contributions, and by keeping this boilerplate intact I confirm that Sentry can use, modify, copy, and redistribute my contributions, under Sentry's choice of …

Fix Account User activation

---

shared/django_apps/codecov_auth/models.py
tests/unit/django_apps/codecov_auth/test_codecov_auth_models.py

This is for displaying the correct plan to the user if they are in an Account.

account pretty_plan overrides org pretty_plan

---

shared/bundle_analysis/report.py
tests/unit/bundle_analysis/test_bundle_analysis.py
tests/unit/bundle_analysis/test_bundle_comparison.py

This PR contains a couple of improvements:
- Removes `BundleAnalysisReport.db_session` completely, so it should not be possible to leak an open DB handle anymore.
- Within `BundleAnalysisReport.associate_previous_assets`: avoid an N+1 query by moving it out of the loop.
- Similarly, also moves the `set` out of the inner loop, which might reduce the total number of `UPDATE` calls.
- Updates a bunch of tests to properly `cleanup` the `BundleAnalysisReport` and its temporary file.
Related to https://github.com/codecov/internal-issues/issues/650, Although I’m unsure whether this completely fixes that problem.
---
Feel free to review with "ignore whitespace" as most of this is just indentation changes.

Do not expose `BundleAnalysisReport.db_session`

---

shared/bundle_analysis/comparison.py
tests/unit/bundle_analysis/test_bundle_comparison.py

Adds `percentage_delta` for bundle analysis comparison.
This is because status configuration allows users to set a _percentage_ threshold for changes (to fail commit status and whatnot).
To make is easy to compare I'm adding the function that gives us the data, as specified in the function docstring

feat: percentage delta

---

shared/bundle_analysis/db_migrations.py
shared/bundle_analysis/migrations/v003_modify_gzip_size_nullable.py
shared/bundle_analysis/models.py
shared/bundle_analysis/parsers/v2.py

Make a SQLite migration to make it so that gzip size is nullable and when parsing `gzipSize` handles the case that the value can be null.

Bundle analysis: make gzip size nullable

---

shared/validation/validator.py
tests/unit/validation/test_validation.py

context: https://github.com/codecov/engineering-team/issues/2223
it seems that we get a validation error when trying to coerce the bundle_analysis threshold.
I can only assume it's the use of DJango database from an async context, so removing that.

fix: cant use flags in validator?

---

shared/validation/user_schema.py
tests/unit/validation/test_validation.py

There were 2 configs with the same name: `comment.bundle_analysis_threshold`
and `bundle_analysis.bundle_analysis_threshold`. They are similar but will be kept
separate. One is the threshold to create a comment, the other to emit warnings or fail
a status.
To help differentiate them we are renaming one. Because `comment.bundle_analysis_threshold` is already used it's easier to rename the other one.

chore: rename bundle_analysis.bundle_analysis_threshold

---

shared/github/__init__.py
tests/unit/github/test_github_installation_helpers.py

It seems that `celery` unpickles exceptions for some reason.
I suppose it can't do that with `InvalidInstallationError` because I was not passing all args.
Indeed the full log error is
`UnpickleableExceptionWrapper('shared.github', 'InvalidInstallationError', (), 'InvalidInstallationError()')`
Where we see it trying to create the exception with a `()` (empty tuple) for args.
Passing all args should fix this, I hope.

fix: unpickleable exception

---

shared/bots/github_apps.py
shared/bots/helpers.py
shared/django_apps/legacy_migrations/management/commands/migrate.py
shared/helpers/redis.py
shared/torngit/cache/__init__.py
shared/torngit/github.py
tests/unit/helpers/test_redis.py
tests/unit/rate_limits/test_rate_limit.py
tests/unit/torngit/test_cache.py

The function that gets installation tokens is cached so we don't ask for them so often.
However the cache was not being initialized.
SO the increase in requests is probably being interpreted by GitHub as rate limit violation and now we are getting 403s left and right :E
These changes configure the cache (I had to move some redis funcitons) and extends the timeout to 30minutes. THe [docs](https://docs.github.com/en/apps/creating-github-apps/authenticating-with-a-github-app/generating-an-installation-access-token-for-a-github-app) say they expire after 1h, so this should be safe to do.

fix: configure cache for installation tokens

---

shared/bundle_analysis/models.py
shared/bundle_analysis/parsers/v1.py
shared/bundle_analysis/parsers/v2.py
shared/bundle_analysis/report.py
tests/unit/bundle_analysis/test_bundle_analysis.py

Also have the ingester return the bundle name of the parsed bundle file, this is an optimization for worker to save BA measurements data.
Note: only merge this when the worker PR to match the new ingest function signature is ready to be merged.

bundle analysis: save custom compare sha to metadata

---

shared/github/__init__.py
tests/integration/test_bots.py
tests/unit/test_github.py

We are still being hit by many invalid installation errors.
The `permission_error` real cause is still not unclear. At first the suspicion
was suspended apps, but that is not the whole story (from empirical data).
I suspected rate limit errors, and we discovered an unconfigured cache at some point.
That has been remedied but the errors are still going strong.
These changes attempt to further breakdown the responses we get to help with debugging.
Mostly it will verify if the issue is indeed with rate limit or not.

chore: adding more causes for InvalidInstallationError

---

shared/bundle_analysis/comparison.py
shared/bundle_analysis/models.py
shared/bundle_analysis/report.py

When doing comparisons first check if there is a compare_sha set in the head report, if there is use that commitid to load the base commit report to compare the head to.

bundle analysis: compare base commit with pre commit merge SHA

---

shared/bots/github_apps.py
tests/integration/test_bots.py
tests/unit/bots/test_github_apps.py

In commit 6637dcc392d7adde051948cb9053201fd0e9cbda we added a further breakdown
of why `InvalidInstallationError` was raised when trying to get the access_token.
In particular the body of the response tells us if the installation is suspended,
which is quite convenient.
Scrolling through the events in Sentry for that issue - [example](https://codecov.sentry.io/issues/5619600100/events/d9d0c0f6e66a43dba92e4d0021b9f0fa/?project=4165036&query=is%3Aunresolved+issue.priority%3A%5Bhigh%2C+medium%5D&referrer=previous-event&statsPeriod=7d&stream_index=10&utc=true) - there's quite a few "installation_suspended" entries.
We do have a mechanism to mark installations as suspended, so we don't try to get tokens for those, but it relies on webhooks, and these installations were probably suspended …

chore: mark suspended apps so

---

shared/reports/editable.py
shared/reports/resources.py

According to profiling, emitting the metrics from `EditableReport` functions can add up to 2% of the total `UploadProcessor` timing. It thus makes sense to remove these metrics. The outer `merge` function however was annotated with tracing, as that function does make sense to measure.

Remove excessive metrics

---

shared/celery_config.py

see docs: https://docs.celeryq.dev/en/stable/userguide/optimizing.html#prefetch-limits
We want to reudce the number of tasks that are prefetched by workers, following celery docs suggestion:
> If you have many tasks with a long duration you want the multiplier value to be one: meaning it’ll only reserve one task per worker process at a time.
Most of our tasks are long running, and we have experienced a considerable number of tasks
being "in a limbo". So reducing the number of prefetched tasks might help with that too.

reduce prefech limit

---

shared/validation/validator.py
tests/unit/validation/test_validation.py

With the release of the `new_notify` for bundle analysis we should be OK to clean the rollout.
Part of https://github.com/codecov/engineering-team/issues/2087

chore: clear rollout

---

shared/bots/github_apps.py

Seeing a couple of issues in Sentry about key error, https://codecov.sentry.io/issues/?groupStatsPeriod=auto&project=4165036&query=is%3Aunresolved+issue.priority%3A%5Bhigh%2C+medium%5D+KeyError&referrer=issue-list&statsPeriod=3h&stream_index=6. I tracked it down to this line, https://github.com/codecov/shared/blob/114034600da5b7a3f974a5201b5c51917617bc50/shared/bots/github_apps.py#L323-L324, being called, where the GithubInstallationInfo only returns the installation_id, so I'm using that key instead of the id. I verified this key being unique from GH's side, so we can safely filter by that key. The only drawback is that the installation_id isn't indexed, so the filtering logic might take a bit more time (but we can add an index in a followup PR)
Look, I get it. The entity doing business …

334 v2 adjust installation key

---

.gitignore
setup.py

https://github.com/codecov/internal-issues/issues/726#event-14133511408
i also added `.git` and `.sl` to `.gitignore` so my hookup to run pre-commit hooks with sapling instead of git works :v

update cryptography dep

---

shared/bundle_analysis/report.py
tests/unit/bundle_analysis/test_bundle_analysis.py

Add a function for BundleReport to fetch gzip size total

bundle analysis: add gzip size total for report

---

shared/api_archive/archive.py
shared/storage/aws.py
shared/storage/base.py
shared/storage/fallback.py
shared/storage/gcp.py
shared/storage/memory.py
shared/storage/minio.py
tests/unit/storage/test_aws.py
tests/unit/storage/test_fallback.py
tests/unit/storage/test_gcp.py
tests/unit/storage/test_memory.py
tests/unit/storage/test_minio.py

The `update_archive` function was the only user of `append_to_file`, but itself is not used anywhere.
Thus the `append_to_file` function can be removed. It was problematic in itself, as it did not guarantee atomic updates.

Remove unused `append_to_file` and `update_archive`

---

shared/torngit/gitlab.py
tests/integration/cassetes/test_gitlab/TestGitlabTestCase/test_get_pipeline_details.yaml
tests/integration/cassetes/test_gitlab/TestGitlabTestCase/test_get_pipeline_details_fail.yaml
tests/integration/test_gitlab.py

related to https://github.com/codecov/engineering-team/issues/2076
Apparently there are situations in which we want to post the commit checks to more than one commit, for GitLab (when merge result pipelines are enabled).
In order to do this we have basicaly 2 options:
1. Get the extra commit SHAs, or
2. Save the extra commit SHAs.
I don't think this is such a common situation for us, so that the cost of some extra
requests to GitLab are less than the cost of making changes to the database to save the
extra info (CLI sends extra SHA and it's saved in the Upload).
So these changes introduce the endpoint that let's us get the pipeline details to see
if we need to send commit statuses to multiple SHAs.
The project ID is `Repository.service_id` and the job ID is `ReportSession.job_code`.

feat: add get_pipeline endpoint

---

shared/upload/constants.py

part of https://github.com/codecov/engineering-team/issues/1520
related to https://github.com/codecov/worker/pull/703
API has a version of this enum, and worker just uses magic strings. it turns out this is important for displaying user-friendly error text in the UI so it is important to be consistent. this PR creates an enum that i'll make worker and API use

add UploadErrorCode enum for use in worker/api

---

shared/validation/user_schema.py

Following up from https://github.com/codecov/codecov-api/pull/780/files#diff-f880df5913bd1613d329d68bfa71ad888ed8ac3e76069bc5ed72bf72e75c3272

[chore] Deprecate allow coverage offsets yaml field

---

shared/bundle_analysis/comparison.py
tests/unit/bundle_analysis/test_bundle_comparison.py

The design for https://github.com/codecov/engineering-team/issues/1491 includes warnings in the bundle table for individual bundles.
In order to do that we need a percentage change on the bundle level. The calculation of percentage follows the same idea as the `Comparison`: the percentage is taken using the base bundle size as the 100%
Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. In 2022 this entity acquired Codecov and as result Sentry is going to need some rights from me in order to utilize my contributions in this PR. So here's the deal: I retain all rights, title and interest in and to my contributions, and by keeping this boilerplate intact I confirm that Sentry can use, modify, copy, and …

feat: add percentage change for bundles

---

shared/django_apps/core/managers.py

This PR aims to fix these related sentry issues:
https://codecov.sentry.io/issues/5334155312
https://codecov.sentry.io/issues/5409774549
https://codecov.sentry.io/issues/5215132965
https://codecov.sentry.io/issues/5820085486
https://codecov.sentry.io/issues/5441235127
That seem to all be related to a unique_constraint error when trying to create this object when a similar one already exists. Thanks @adrian-codecov for talking me through this one
Unique constraint comes from here: https://github.com/codecov/shared/blob/b42ecbe84e6cf1e0d8cfdab6dc5beb12600e06b3/shared/django_apps/core/models.py#L157-L163
Related django documentation: https://docs.djangoproject.com/en/5.1/ref/models/querysets/#update-or-create
Look, I get it. The entity doing business as "Sentry" was incorporated in the State …

fix: use update_or_create instead of get_or_create depending on the webhook response

---

shared/bundle_analysis/report.py

Don't use raw sql for the update statements, use ORM queryset notations.
closes https://github.com/codecov/engineering-team/issues/1846

bundle analysis: ref: SQLAlchemy update statements

---

shared/reports/readonly.py
shared/reports/resources.py

A bunch of these traces are just forwarding to the child `Report`, and add little value on their own.

Remove tracing from `ReadOnlyReport`

---

shared/django_apps/core/managers.py

This PR removes duplicate log entries that were causing test failures in API

fix: Logs that have duplicate entries in GH webhook code

---

shared/torngit/github.py

There was a slight miscommunication on this. The bot's name is not `sentry-ai` in production, it is just `sentry`. This commit rectifies this error.

Update Sentry Bot Name

---

shared/bots/__init__.py
shared/torngit/base.py
shared/torngit/bitbucket.py
shared/torngit/github.py
shared/torngit/gitlab.py
shared/torngit/response_types.py
shared/typings/torngit.py

adds back the type hints that were removed when we reverted https://github.com/codecov/shared/commit/62ef7b37c2a2fd0e192939e3f776d99d7fcc045b

chore: add ProviderPull type

---

shared/torngit/github.py

we saw a strange request recently that returned a 200 but was unexpectedly missing all the rate limit headers and it took 5 seconds. seems like something might have been up with it, but we had no way to ask GH support to take a look

log `x-github-request-id` in torngit github

---

shared/torngit/github.py

This PR Changes the copy for the copilot button to more clearly indicate the function of the button itself (i.e., to generate tests). 
Also  makes the sentry message in chat a complete sentence.

Change Copilot Copy

---

shared/yaml/fetcher.py

We are importing the modules to reference other modules/files. But it's better practice to import the specific thing that you want to import instead.

Make imports more atomic and explicit

---

shared/yaml/validation.py
tests/unit/validation/test_validation.py

This change disallows the `to_string` key to be present during the validation of codecov YAML, if whenever the key is in the YAML string then it will fail with validation error. We need this reserved key in order to keep a copy of the owner YAML's full string content allowing to display original formatting and comments.
Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. In 2022 this entity acquired Codecov and as result Sentry is going to need some rights from me in order to utilize my contributions in this PR. So here's the deal: I retain all rights, title and interest in and to my contributions, and by keeping this boilerplate intact I confirm that Sentry can use, modify, copy, and redistribute my …

Update YAML validator to drop reserved key for internal use only

---

shared/validation/helpers.py

log: add the relevant glob to a warning log about globs

---

setup.py
shared/reports/resources.py
tests/integration/test_report.py
tests/unit/test_report.py

This is the same as https://github.com/codecov/worker/pull/772, and for the same reasons: `orjson` is advertised as being 3x faster for deserialization, and up to 10x faster for serialization.

Switch to `orjson` for Report de/serialization

---

shared/bundle_analysis/db_migrations.py
shared/bundle_analysis/parser.py
shared/bundle_analysis/parsers/base.py
shared/bundle_analysis/parsers/v1.py
shared/bundle_analysis/parsers/v2.py
shared/bundle_analysis/report.py

Small addition to tracing of some functions related to BA reports.
And some small fixes so VS Code would stop complaning about types.
ps.: `ParserTrait` might not be the best name for what that class is...
it's not very pythonic in any case

chore: improve typing and tracing of BA reports

---

shared/django_apps/core/tests/factories.py
tests/unit/django_apps/core/test_core_models.py

This primarily removes usage from other test fixtures.

Remove usage of `ReportDetails`/`files_array`

---

shared/rollouts/__init__.py

the sum of all `Feature` variants' proportions is supposed to equal 1.0, but when a `Feature` is first created it has no variants and so that sum will be 0.0. we don't want to spam logs while that is the case
also, a `Feature` that is really only meant to be used via overrides doesn't really need proportions adding to 1.0

stop logging warnings about invalid rollouts for unconfigured rollouts

---

shared/django_apps/codecov_auth/models.py

We have this on `Repository` model so we can do [this](https://github.com/codecov/codecov-api/blob/f48452449f88a23715104f3bc17027d7c094563b/core/signals.py#L27) in `api`.
I'd like to add the same thing for `Owner` to use in the same way in `api`.
ChatGPT says it's performant 👼 
https://github.com/codecov/engineering-team/issues/2299

add FieldTracker to Owner - no migration required!

---

shared/torngit/github.py
tests/unit/torngit/test_github.py

This PR aims to allow our users making a github API request who face a timeout or network error to still retry their API request until the max amount of retries has been reached.
Previously we were throwing an error immediately in these cases.
Closes https://github.com/codecov/feedback/issues/542
Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. In 2022 this entity acquired Codecov and as result Sentry is going to need some rights from me in order to utilize my contributions in this PR. So here's the deal: I retain all rights, title and interest in and to my contributions, and by keeping this boilerplate intact I confirm that Sentry can use, modify, copy, and redistribute my contributions, under Sentry's …

fix: Only throw TorngitServerUnreachableError when no retries left

---

shared/celery_config.py
shared/django_apps/reports/tests/factories.py
shared/storage/minio.py

- add task names for `cache_test_rollups_task` and `cache_test_rollups_redis_task`
- add function overloads for `StorageService.read_file`
this is to support the PRs in API and worker for caching test rollup aggregation results

Cache Test Rollups Support PR

---

setup.py
shared/torngit/bitbucket_server.py
tests/integration/test_bitbucket_server.py
tests/unit/torngit/test_bitbucket_server.py

This pretty much copied over the oauth-related code from `Bitbucket` to `BitbucketServer`, and gets rid of the `oauth2` and `tlslite-ng` dependencies.
This does a few simplifications compared to the `Bitbucket` code, namely not caring about non-json `body`s, as I believe the existing code will only ever pass JSON payloads.
---
fixes part of https://github.com/codecov/internal-issues/issues/436
prerequisite for https://github.com/codecov/shared/pull/423

Migrate `BitbucketServer` to `oauthlib`

---

shared/helpers/cache.py
tests/unit/helpers/test_cache.py

fixes https://github.com/codecov/internal-issues/issues/961
if the value being cached is not JSON-serializable, it will simply give up on caching it rather than raise an exception. an error will be logged to GCP so we should be able to see that occurring in GCP Logs Explorer. but from local testing i couldn't find any issues
BEWARE: technically Python allows dicts with non-`str` keys to be serialized into JSON because it coerces all keys to `str`:
```python
>>> json.loads(json.dumps( {1: 'abcde'} ))
{'1': 'abcde'}
```
this cache change will log an error and skip caching to err on the safe side

remove pickle usage in redis-backed cache helper

---

.envrc
docker-compose.yml
uv.lock

This simplifies the `direnv` config a bit. As `uv sync` is so fast, we can just unconditionally run it. A local `uv sync` has also removed some dependencies from the lockfile which have been removed from the dependencies.
Also adjust the docker images, downgrading `redis` to match the version we are actually running, and picking a lighter-weight `timescaledb` image which should be quicker to download.

Adjust docker images and direnv config

---

shared/torngit/github.py

BA doesn't need this copilot button to appear in them, so I'm adding a variable to enable/disable that button

2876 remove copilot btn from ba pr comment

---

shared/bundle_analysis/utils.py
shared/helpers/cache.py
tests/unit/bundle_analysis/test_bundle_utils.py

For https://github.com/codecov/engineering-team/issues/2570
Given a file path/name of a module we want to compute what route of the application this file belongs to. This class aims to make that transformation by applying custom file based routing rules for various supported plugins. Supported plugins are:
- Remix
- NextJS Webpack
- Nuxt
- SolidStart
- SvelteKit
Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. In 2022 this entity acquired Codecov and as result Sentry is going to need some rights from me in order to utilize my contributions in this PR. So here's the deal: I retain all rights, title and interest in and to my contributions, and by keeping this boilerplate intact I confirm that Sentry can use, …

Bundle Analysis: Make a lib to fetch route by a file name

---

shared/api_archive/archive.py
shared/storage/base.py
shared/storage/minio.py

This removes a bunch of unused functions which are not being used by `api`, as well as fix correctly passing the `is_already_gzipped` parameter.

Clean up `ArchiveService`

---

shared/bundle_analysis/report.py
shared/bundle_analysis/utils.py
tests/samples/sample_bundle_stats_asset_routes.json
tests/unit/bundle_analysis/test_bundle_analysis.py
tests/unit/bundle_analysis/test_bundle_utils.py

Update AssetReport to add a function (that uses the Asset Route lib) to get all routes from the application associated to it.
- Also add a helper function in BundleReport to fetch an asset by its hashed name, this will be useful later.

Bundle analysis: add ability to fetch routes of an asset report

---

shared/bundle_analysis/db_migrations.py
shared/bundle_analysis/migrations/v004_add_dynamic_imports.py
shared/bundle_analysis/models.py
shared/bundle_analysis/parser.py
shared/bundle_analysis/parsers/__init__.py
shared/bundle_analysis/parsers/v3.py
tests/samples/sample_bundle_stats_dynamic_imports_1.json
tests/samples/sample_bundle_stats_dynamic_imports_2.json
tests/unit/bundle_analysis/test_bundle_analysis.py

- Add a DB migration to create a new table (dynamic_imports), this table is a fk mapping between chunks and assets to specify what dynamically imported assets a chunk has.
- Add a new v3 JSON stats file parser that reads chunk.dynamicImport array of strings and stores this into the dynamic_imports table
Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. In 2022 this entity acquired Codecov and as result Sentry is going to need some rights from me in order to utilize my contributions in this PR. So here's the deal: I retain all rights, title and interest in and to my contributions, and by keeping this boilerplate intact I confirm that Sentry can use, modify, copy, and redistribute my contributions, under …

Bundle Analysis: add ability to ingest dynamic imports

---

shared/upload/constants.py

a significant number of "unknown errors" that we report to users are timing out during processing. this PR creates an error code for it, and we can later choose to display different text in gazebo for that error code
note: worker will _attempt_ to set this error code and save everything when it gets the "soft timeout" signal. but there is no guarantee it won't be forcibly killed before it can save everything. there will still be some unknown uploads from that
sibling PR in gazebo: https://github.com/codecov/gazebo/pull/3522

add PROCESSING_TIMEOUT upload error code

---

shared/bundle_analysis/__init__.py
shared/bundle_analysis/comparison.py
shared/bundle_analysis/parsers/v3.py
shared/bundle_analysis/report.py
tests/samples/sample_bundle_stats_dynamic_import_routing_1.json
tests/samples/sample_bundle_stats_v3_comparison_base_1.json
tests/samples/sample_bundle_stats_v3_comparison_base_2.json
tests/samples/sample_bundle_stats_v3_comparison_head_1.json
tests/samples/sample_bundle_stats_v3_comparison_head_2.json
tests/unit/bundle_analysis/test_bundle_analysis.py
tests/unit/bundle_analysis/test_bundle_comparison.py

- Adds a BundleRouteReport to retrieve total size of each route to enable comparisons
- Adds a BundleRoutesComparison to do comparisons between base and head BundleRouteReports. This will be used by PR comments.
closes: https://github.com/codecov/engineering-team/issues/3032

Bundle Analysis: Routing report and comparisons

---

shared/storage/__init__.py
tests/unit/storage/test_init.py

we currently do storage service caching in the worker with the reason that the initialization cost is non-trivial. i'm moving this caching to the shared layer, mostly because of the new minio rollout but also because it generally feels like a good idea (since it's been a good idea to do it in the worker).
There will be a change in the worker that will remove its layer of caching.
Maybe eventually, we will find that the complication of doing this caching is not worth it performance wise.

feat: do storage service caching in shared

---

shared/bundle_analysis/comparison.py
shared/bundle_analysis/utils.py
tests/unit/bundle_analysis/test_bundle_comparison.py
tests/unit/bundle_analysis/test_bundle_utils.py

- Add Astro plugin to the list of supported plugins that can have info about asset routes.
- Also fix an issue with comparisons where base and head may not have the same bundles.
https://github.com/codecov/engineering-team/issues/3057

Bundle Analysis: Add Astro plugin to routing info

---

shared/plan/service.py
tests/unit/plan/test_plan.py

Needed for https://github.com/codecov/codecov-api/pull/1039, This PR adds the properties being fetched by the resolvers
Related Ticket -- https://github.com/codecov/engineering-team/issues/2996

feat: Add new properties for is____Plan on Plan Service

---

shared/reports/types.py
shared/torngit/base.py
shared/torngit/github.py
shared/typings/torngit.py

The copilot AI button appears in every PR comment but should not appear in the BA PR comment. This solution adds a way to specify the upload type and manipulate the data being sent to GH.

Add conditional based on upload type

---

shared/plan/constants.py
shared/plan/service.py
tests/unit/plan/test_plan.py

Needed for available plans data type.

feat: Map helper functions to available plans

---

shared/plan/constants.py

Update with value instead of keys for plan data dict

---

shared/torngit/base.py

The database has a set of enum validation which is different from the in-code validation that we do when checking that the language is valid. This should ensure that the language set looks the same.
Resolves this issue: https://github.com/codecov/engineering-team/issues/2061
Might want to try this in worker/staging before merging because it uses a Django property.
Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. In 2022 this entity acquired Codecov and as result Sentry is going to need some rights from me in order to utilize my contributions in this PR. So here's the deal: I retain all rights, title and interest in and to my contributions, and by keeping this boilerplate intact I confirm that Sentry can …

Ensure that language validation works on all supported languages

---

shared/django_apps/bundle_analysis/service/bundle_analysis.py
shared/django_apps/bundle_analysis/tests/service/test_bundle_config.py

Add get_or_create, will have to use this instead of update_or_create in the BA processor. Currently we will always overwrite what the caching bool to true when doing a new commit into default branch. When switching to this the intention is that if the bundle cache data already exists we will not overwrite it to true.
Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. In 2022 this entity acquired Codecov and as result Sentry is going to need some rights from me in order to utilize my contributions in this PR. So here's the deal: I retain all rights, title and interest in and to my contributions, and by keeping this boilerplate intact I confirm that Sentry can use, modify, copy, and redistribute my …

[Bundle Analysis] Cache config service get_or_create

---

shared/upload/utils.py
tests/unit/upload/test_utils.py

Create batch insert fn for user measurements

Add batch insert fn for measurements

---

pyproject.toml
shared/django_apps/utils/model_utils.py
shared/encryption/token.py
shared/license/__init__.py
tests/integration/test_gitlab.py
tests/unit/bundle_analysis/test_bundle_analysis.py
tests/unit/test_license.py
uv.lock

Looks like our CI checks are enforcing formatting using the very latest Ruff version which was just released and has slightly changed formatting: https://astral.sh/blog/ruff-v0.9.0
This PR updates the local dev dependency version, and bulk-reformats everything.

Reformat with `ruff>=0.9`

---

shared/helpers/cache.py
shared/torngit/base.py
shared/torngit/cache/__init__.py
shared/typings/oauth_token_types.py
shared/typings/torngit.py

Some relevant decisions:
* `timeout` passed to `TorngitBaseAdapter.__init__` is transformed into `httpx.Timeout` directly, (so that `self._timeout` can be directly an `httpx.Timeout` object instead a bunch of different options
* `verify_ssl` receives the default value of `True`. That shouldn't break anyone except BB server. (but no one is using it, so as I said it shouldn't break anyone)
* Better differentiation of aouth_consumer_token and token. They are actually different things.

chore: some type updates

---

shared/helpers/cache.py
shared/torngit/base.py
shared/torngit/cache/__init__.py
shared/typings/oauth_token_types.py
shared/typings/torngit.py

We just had major issues in the api because of apparently we are passing a list and the verification was not there anymore.
But in any case we are adding back the verification that timeout is a list.

revert other commit

---

shared/billing/__init__.py
shared/django_apps/codecov_auth/models.py
shared/plan/constants.py
shared/plan/service.py
tests/unit/plan/test_plan.py

update PlanService so GitLab orgs use the root org's plan, fold is_pr_billing_plan into PlanService
IF an OwnerOrg is a GitLab subgroup OR has an Account, the `plan` on the OwnerOrg is not the one we want to use! We want the `plan` on the root Org or Account object instead.
PlanService already had the smarts to check for an `Account` and get the Account `plan`, but now it also has the smarts to check whether a GitLab OwnerOrg has a parent, then use the `plan` from the root Org. 
Part of https://github.com/codecov/engineering-team/issues/2710

PlanService updates for GitLab

---

shared/rollouts/features.py
shared/storage/__init__.py
tests/unit/storage/test_init.py

we want to start by rolling the worker out to use the MinioStorageService for only our repos, then incrementally roll it out to more users

Add USE_MINIO feature flag

---

shared/django_apps/core/tests/factories.py

Whic working on the repo cleanup, I noticed frequent test failures related to `Branch.name` not being unique enough. This fixes that along with some other improvements, like being able to use `CommitWithReportFactory` in `worker` which was not possible previously because of imports that are only valid within `api`.

Slightly improve test factories

---

shared/plan/service.py
tests/unit/plan/test_plan.py

use current_org.activated_user_count instead of plan_activated_users since activated_user_count does not include users with student=True in its calculation

fix: has_seats_left property

---

shared/events/amplitude/publisher.py
tests/unit/events/test_amplitude.py

Sets org=ownerid when ownerid is passed as an event property. This is something I forgot to do in the first iteration, but is the intended behavior for mapping events to orgs.

feat: Add org user group to events with ownerid property

---

tests/unit/django_apps/codecov_auth/test_codecov_auth_models.py

This PR aims to add a test for the default free plan on owner. It'll error out if that plan isn't available in the DB

dev: Add test for default free plan

---

shared/django_apps/codecov_auth/migrations/0065_alter_account_plan_alter_owner_plan.py

This PR updates the plan type part of the migration to be "risky" basically failing and continuing if the type alteration encounters an error
**Testing**
- Tested locally by deleting the migrations from my DB
- Updated https://github.com/codecov/shared/blob/6c6d5a11ff63ae9b927c1e69409ba4643c37e145/shared/django_apps/dummy_settings.py#L70-L71 to True
- Re-ran migrations and confirmed it ran successfully
Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. In 2022 this entity acquired Codecov and as result Sentry is going to need some rights from me in order to utilize my contributions in this PR. So here's the deal: I retain all rights, title and interest in and to my contributions, and by keeping this …

fix: Add RiskySQL to alter type plans

---

shared/django_apps/reports/tests/factories.py
shared/upload/constants.py

New error supported by worker for uploads.  

chore: Add `unsupported_file_format` as part of upload errors enum

---

shared/reports/carryforward.py
shared/reports/filtered.py
shared/reports/readonly.py
shared/utils/match.py

This introduces a stateful `Matcher` class that is used to implement the `match/_any` fns.
This can be used to avoid compiling regex matchers repeatedly.

Optimize `match/_any`

---

shared/events/amplitude/publisher.py
shared/events/amplitude/types.py
tests/unit/events/test_amplitude.py

Adds the required event properties for the Amplitude 'Upload Sent' event that will be instrumented in API after this is merged.

feat: Add required event properties for Amplitude upload event

---

shared/storage/minio.py
tests/unit/storage/test_minio.py

we're running into [this issue](https://codecov.sentry.io/issues/6293115637/events/11ab665a53664b6ca25b923a37eac0f7/) on Sentry, and given the docs [here](https://cloud.google.com/storage/docs/retry-strategy#python) i want to try and change some of our HTTP retry settings

fix: handle Minio client retries better

---

.coveragerc
.github/workflows/ci.yml
.gitignore
Makefile
docker-compose.yml

useful for https://github.com/codecov/umbrella/pull/4

ci: use same coverage/test result filenames as other repos

---

shared/storage/new_minio.py

We were running into a [S3Error in Sentry](https://codecov.sentry.io/issues/6313961939/events/ce6eb9249f614f26b0ff662de9362882/) when we enabled the new Minio storage backend and this is the fix for that. The reason we were passing these headers in the first place was due to the docs [here](https://cloud.google.com/storage/docs/transcoding). 
The only difference between the requests was that this header was being set so I removed it to see if it would fix the error in staging and it did.

fix: new minio storage service

---

shared/django_apps/codecov_auth/models.py
tests/unit/django_apps/codecov_auth/test_codecov_auth_models.py

Adds two new properties to the Owner class for use from the FE for use in this ticket https://github.com/codecov/engineering-team/issues/3074
Related codecov-api PR: https://github.com/codecov/codecov-api/pull/1168

feat: Add hasPublicRepos and hasActiveRepos owner props

---

shared/reports/editable.py
shared/reports/resources.py
tests/unit/reports/test_editable.py
tests/unit/test_report.py

This removes the existing implementation on `Report`, as only the `EditableReport` is supposed to have them. It also removes the single `delete_session` in favor of the `delete_multiple_sessions` method.
The remaining method is optimized slightly.

Clean up `delete_session` related code

---

shared/api_archive/archive.py
shared/api_archive/storage.py

Previously, the archive service uses the storage service (not base storage service) used the minio service, which can't read files written by the new minio service, so when we enabled the new minio feature the archive service started failing.
This change makes it so the storage service uses the new minio service based on the value of the feature flag.

fix: archive service bug in sentry

---

shared/events/amplitude/__init__.py
shared/events/amplitude/constants.py
shared/events/amplitude/publisher.py
tests/unit/events/test_amplitude.py

Adds constants for using an anonymous user with Amplitude.

feat: Add anonymous user details for amplitude

---

shared/reports/filtered.py
shared/reports/resources.py
shared/reports/totals.py

In particular, this unifies the duplicated implementations of these methods across `Filtered/ReportFile`.
The new method also spells out a "very concise, but also unreadable" implementation that sums up the cyclomatic complexity (something I would like to remove completely eventually). This is now more readable and understandable, but more importantly, it only iterates over the `lines` *once*, instead of twice as the previous implementation did. Along with avoiding a bunch of intermediate list allocations that the `FilteredReportFile` implementation did, this should yield quite a good speedup.
---
I get the following benchmarks results now locally (as sadly, benchmarks are not yet fully working in CI):
```
Benchmark Results …
```

Consolidate implementation of `_process_totals`

---

shared/reports/readonly.py
tests/unit/reports/test_readonly.py

This method seemed to have been intended to warn about wrong usage of `ReadOnlyReport`.
I checked both in production logs, as well as scanning through the code, and it looks like we are not misusing the this report class in such a way. So it is safe to remove this warning.

Remove unused `ReadOnlyReport.append`

---

shared/reports/editable.py
shared/reports/resources.py
tests/integration/test_report.py
tests/integration/test_report_file.py
tests/unit/test_report.py
tests/unit/test_report_file.py

The base `Report` and `ReportFile` classes had some code related to filtering which was never actually used, as filtering works using the `FilteredReport` class.

Remove unused filtering code from `Report/File`

---

shared/reports/diff.py
shared/reports/filtered.py
shared/reports/resources.py
tests/unit/reports/samples/test_filtered.py

This cleans up the duplicated implementations of `Filtered/Report.calculate_diff` and moves it to a new well typed file.
---
I’m a bit surprised that this does not yield any speedup in the diff calculation benchmarks (compared to https://github.com/codecov/shared/pull/525).
I think the difference between the base and `FilteredReport` is based on the actual filtering and line-mapping code that happens, instead of the different and less optimized version that was previously there.
```
Benchmark Results                                          
┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━┳━━━━━━━━━━┳━━━━━━━━┓
┃                                       Benchmark ┃   Time (best) ┃ Rel. StdDev ┃ Run time ┃  Iters ┃ …
```

Consolidate implementation of `calculate_diff`

---

shared/reports/resources.py
tests/benchmarks/test_report.py

In particular, this better highlights the difference between a shallow and a full parse of the Report.
It also focuses the `totals` code a bit more, making the different operations more obvious. The filtering has also been slightly updated.
As a driveby fix, this fixes the `Report.get(bind)` code, which was completely broken (because noone was using it?)

Make some benchmark code more explicit

---

shared/reports/editable.py
tests/unit/reports/test_editable.py

This is a first step moving that function, before further work in `shared` can happen to merge the `EditableReport` back into the main `Report` class.
---
This is part of https://github.com/codecov/engineering-team/issues/3381

Port `change_sessionid` from `worker`

---

shared/api_archive/archive.py
shared/storage/__init__.py

The recent change to the `api_archive.ArchiveService` meant that all the mocks that target `get_appropriate_storage_service` within `worker` stopped working.
This fixes the mocking within `worker` by making sure that we always go through `get_appropriate_storage_service`.

Make `api_archive` mockable again

---

shared/reports/diff.py
tests/unit/reports/samples/test_filtered.py

This was a recent regression from consolidating the diff calculation. Downstream code expects/asserts the `complexity/_total` to be `None` when no lines have been touched by the diff.

Set `complexity/_total` to `None` in diff calculation

---

shared/events/amplitude/metrics.py
shared/events/amplitude/publisher.py
tests/unit/events/test_amplitude.py

This PR adds an `_unsafe_publish` method to the Amplitude event publisher, converting the existing `publish` method to be safe by default (i.e., it will always fail gracefully).
Also adds prometheus metrics to track success and failures of amplitude publish calls.

feat: Make Amplitude publish fail gracefully

---

.github/workflows/ci.yml

github puts a merge commit at the top of every PR. the CLI is supposed to detect that and use the actual PR head as the SHA instead of the merge commit, but because we were missing this fetch-depth argument, the local checkout only had the merge commit in it.

fix ci: add fetch-depth: 2 to checkout step to fix codecov

---

shared/reports/editable.py
shared/reports/resources.py
shared/reports/types.py
tests/integration/test_report.py
tests/integration/test_report_file.py
tests/unit/reports/test_editable.py
tests/unit/test_report.py

The main purpose of the `EditableReportFile` was to offer methods to delete labels/sessions, as well as to properly maintain uptodate versions of `present_sessions` and `totals` when doing mutations on the file.
All the methods were now moved to `ReportFile`, which has also gained new functionality related to making sure that caches are cleared when necessary, and re-computed on-demand, so that they are always correct.
---
I plan to do a similar thing for `EditableReport` as well in a followup, as it has a similar purpose in relation to maintaining uptodate `totals`.
This is part of https://github.com/codecov/engineering-team/issues/3381

Merge `EditableReportFile` into `ReportFile`

---

shared/torngit/github.py

getting a type error with the TypedDict when using the dict syntax to create the ProviderPull in github.py and using the {} syntax fixes this

refactor: use dict {} syntax for typing

---

.github/workflows/ci.yml

The walltime instrumentation is only usable on codspeed bare metal runners, which we don’t currently use.
In the meantime, it would be nice to get *some* kind of result for the benchmark, even if it takes a long time.

Switch benchmarks back to instrumentation mode

---

shared/reports/readonly.py
shared/reports/resources.py

The `api_report_service.ReadOnlyReport` overrides the `flags` property, but it looks like the usage of `.flags` would be better served by `get_flag_names` instead.
But that method previously did not exist on that `Report` class, so lets add it.

Forward `get_flag_names` for the `ReadOnlyReport`

---

shared/torngit/github.py

Adds a Sentry message when the github oauth token is refreshed but the token refresh callback is not defined. This should not be able to occur, but this could explain the behaviour we're seeing.

debug: Add debug log to token refresh logic

---

shared/metrics/__init__.py
shared/storage/minio.py
shared/storage/write.py

having trouble loading aggregates for a week in sentry so want to send metrics to prom as well in case it performs better

chore: add prom metrics to minio storage service

---

tests/benchmarks/test_report.py

We were previously also benchmarking the `ReadOnlyReport`. However that has yielded pretty much the same numbers, regardless of the "rust" feature flag. I’m pretty sure that class as it exists now does not pull its weight, and I think we should remove it.
For now, I remove it from the benchmarks, as the benchmarks provide no additional value, but are just slowing down the benchmark suite.

Only benchmark the `Report` class

---

shared/django_apps/db_routers/__init__.py
shared/django_apps/db_settings.py
shared/django_apps/dummy_settings.py
tests/unit/django_apps/test_db_routers.py

we'll just use the default as it's probably faster, but we won't get to scale TA DB separately

fix: remove test_analytics database

---

shared/reports/readonly.py
shared/reports/resources.py
shared/reports/serde.py
tests/integration/test_report.py
tests/unit/reports/test_carryforward.py
tests/unit/reports/test_editable.py
tests/unit/reports/utils.py
tests/unit/test_report.py

I removed the users of the `to_archive`/`to_database` functions, so lets remove those, along with other functions.
Another change is to change the serde code to use `str`. As strange as it might sound, but I believe that python is optimizing strings a bit better, and avoids copying all the string contents around in some cases.
This also cleans up the tests a bit.

Remove more unused `Report` code, change serde code to use `str`

---

shared/django_apps/db_settings.py
shared/django_apps/dummy_settings.py
shared/django_apps/ta_timeseries/migrations/0002_testrun_summary_1day.py
shared/django_apps/ta_timeseries/models.py

- if we have the 2 connections point at the same exact database, it will fail to actually make the migrations because the first one will mark the migrations as done, and the second one will see that they are done and not do anything
- renaming of the indexes to avoid conflicts
- renaming the target table in the continuous aggregates
follow-up here: https://github.com/codecov/worker/pull/1150

fix: quick fix

---

shared/plan/service.py
tests/unit/plan/test_plan.py

This PR aims to fix a bug where a user who has not linked their Sentry account tries to update their plan details while they're on the sentry plan. We naively search for the "available plans" for the user adding the sentry plans to that list if they have the account linked. But we should also add the sentry plans to that list if they're currently on a sentry plan
Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. In 2022 this entity acquired Codecov and as result Sentry is going to need some rights from me in order to utilize my contributions in this PR. So here's the deal: I retain all rights, title and interest in and to my contributions, and by keeping this boilerplate intact I confirm that Sentry can …

fix: Nonsentry user on sentry plan should be able to update plan

---

shared/reports/readonly.py
tests/unit/reports/test_changes.py
tests/unit/reports/test_readonly.py

It turns out that the [`ComparisonProxy.get_impacted_files`](https://github.com/codecov/worker/blob/c87d47b6c64d150f19242c3ef1c3a5821fc0931f/services/comparison/__init__.py#L284-L290) function within `worker` is depending on the `RustReport` being enabled and present.
So lets just remove the feature flag and hard-enable this, to make it clear that other code actually depends on this.

Hard-enable the `RustReport`

---

Makefile

see resulting test file paths here: https://app.codecov.io/gh/codecov/shared/tests/matt%2Fmonorepo-friendly-junit
sort by "Last run" to get the results of the most recent attempt
this is a bit of a hack, but better solutions are all way, way easier after cutover and involve more invasive changes to how things work.
the worker/shared/api PRs pass `--rootdir=${PYTEST_ROOTDIR} -c pytest.ini` to pytest invocations. `--rootdir=${PYTEST_ROOTDIR}` allows us to override the rootdir, and `-c pytest.ini` makes sure pytest can still find its config when we do.
by default, the rootdir is `.`, which is the directory `pytest.ini` lives in. it's as if neither argument were passed at all. the original worker/api/shared repos use the default, so they are unchanged.
[the gha-workflows …

emit junit results in a monorepo-friendly way

---

shared/utils/merge.py
tests/unit/utils/test_merge.py

This is coming from a customer issue.
The customer has an upload that contains both an lcov file as well as a cobertura file.
The lcov file creates a `LineSession` with `0/2` coverage and `missed_branches=[0:5, 0:6]`.
The cobertura file encodes the same information in a different format, yielding `0/1` with `missed_braches=[0]`.
Merging those two is currently broken and yields a bogus result of `2/2`.

Document broken branch merging logic

---

shared/bundle_analysis/parsers/v3.py
tests/samples/sample_bundle_stats_dynamic_imports_3.json
tests/samples/sample_bundle_stats_dynamic_imports_4.json
tests/unit/bundle_analysis/test_bundle_analysis.py

Fixes: https://github.com/codecov/engineering-team/issues/3490
Apparently it is possible to have referenced assets in the `dynamicImports` array that was never declared in the `assets` array, in this case we will ignore it.

Bundle Analysis: Fix handling non-existent dynamic assets

---

shared/django_apps/codecov_auth/models.py

https://codecov.sentry.io/issues/6298875711/events/latest/?environment=dd&project=4505562661847040&query=&referrer=latest-event&sort=date&stream_index=0
I was running into 500s trying to login in to DD's instance. Turns out we were defaulting to plan "users-developer" even though they are DEC and are on a pro plan.
Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. In 2022 this entity acquired Codecov and as result Sentry is going to need some rights from me in order to utilize my contributions in this PR. So here's the deal: I retain all rights, title and interest in and to my contributions, and by keeping this boilerplate intact I confirm that Sentry can use, modify, copy, and redistribute my …

fix: Use default free plan const instead of specific plan

---

shared/torngit/github.py

fix: sync repo languages also syncs forked repos

---

shared/storage/__init__.py
shared/storage/minio.py
tests/unit/storage/test_minio.py

GCS/S3 objects allow you to add metadata to them when writing, and you can read that metadata back. This is done via request/response headers. The reason I chose to pass in a metadata_container instead of changing the return type of read_file is because I wanted to offer the option to not care about an object's metadata, and this also makes it so this PR won't involve a bunch of changes to the call sites  in worker and API and instead i can just change the call sites i actually care about

feat: add metadata to MinioStorageService

---

shared/torngit/github.py

This extends GitHub request caching to the `list_files` and `get_source` functions.
While both can take an arbitrary "mutable" ref, like a branch name, we only call those with an immutable commit sha, which makes these good calls to cache.

Cache more GitHub requests

---

pyproject.toml
shared/helpers/cache.py
uv.lock

We would like to cache `bytes`, which is being rejected by JSON.
msgpack does not have that problem, and should be slightly faster/smaller than JSON in either case.

Switch cache to msgpack

---

shared/django_apps/utils/model_utils.py

This consists of two optimizations:
- It prefers the `archive_field` over the `db_field`, and can thus avoid some queries for the `db_field`, as some queries in API are explicitly `defer`-ing that load.
- It also avoids initializing the `ArchiveService.storage_hash`, which we don’t need for reads (only writes), and which would require us to load the related repository and owner.

Optimize `ArchiveField` reads

---

shared/validation/user_schema.py

The intended flow here will be: 
Shelter gets PR open webhook -> Forward to codecov api and get yaml config value for owner -> If they have auto reviews on, kick off seer workflow for that PR
This PR just adds that yaml config value for the owner 
Importat: The PRs that are part of this flow are either `ready_for_review` or `opened` in a non-draft state. 
Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. In 2022 this entity acquired Codecov and as result Sentry is going to need some rights from me in order to utilize my contributions in this PR. So here's the deal: I retain all rights, title and interest in and to my contributions, and by keeping this boilerplate intact I confirm that Sentry can use, …

[ft] Add allow auto pr review config setting
